### ISSUE TITLE
「2.4.6 見出し及びラベル」への訳注付記

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag20#117]
「2.4.6 見出し及びラベル」では、「十分な達成方法」の「注記」で、
> 達成基準 1.3.1 により、見出し及びラベルは、プログラムで判断できなければならない。
> https://waic.jp/docs/UNDERSTANDING-WCAG20/navigation-mechanisms-descriptive.html

となっています。

翻訳としては、原文に忠実です。
> Headings and labels must be programmatically determined, per Success Criterion 1.3.1 .
https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-descriptive.html#navigation-mechanisms-descriptive-techniques-head

しかし、「1.3.1 情報及び関係性」では、
> 何らかの形で提示されている情報、 構造、及び関係性は、プログラムによる解釈が可能である、又はテキストで提供されている。 (レベル A)

となっていて、2.4.6の「プログラムで判断できなければならない。」という注記だと、「又はテキストで提供されている」ことを否定しているように読めます。

おなじく1.3.1がらみの達成基準である「3.3.2 ラベル又は説明」にも似た注記がありますが、こちらは丁寧に1.3.1に沿った注記になっています。
https://waic.jp/docs/UNDERSTANDING-WCAG20/minimize-error-cues.html#minimize-error-cues-intent-head

くれぐれも全体的な翻訳を非難する意図はないのですが、「WCAG2.0 解説書」は、それなりに読むのに努力を要する文書なので、様々な文脈から理解を構築していく読み方もあると思います。2.4.6の注記は1.3.1の理解の妨げになるように思いますので、訳注付記をご検討いただけませんでしょうか？　以下は、訳注提案です。

> 訳注: 「プログラムで判断できなければならない。」とありますが、達成基準 1.3.1 にあるとおり、「見出し及びラベルは、プログラムで決定できるか又はテキストで利用できなければならない。」と解釈してください。

**Comment by momdo** [comment]
>達成基準 1.3.1 により、見出し及びラベルは、プログラムで判断できなければならない。
>Headings and labels must be programmatically determined, per Success Criterion 1.3.1 .

というのがまず原文に忠実かというと翻訳自体が微妙で、少なくともWCAG 2.0ｂによると、
>プログラムによる解釈 (プログラムによる解釈が可能) (programmatically determined (programmatically determinable))
https://waic.jp/docs/WCAG20/Overview.html#programmaticallydetermineddef

とあるわけですから、ここは、

達成基準 1.3.1 により、見出し及びラベルは、プログラム**による解釈がされ**なければならない。
のような訳出にならないとおかしいのかなあと。（まあもうちょっと訳は検討する必要はあるでしょうが、いずれにせよWCAG 2.0の用語集と整合性があることが求められます。）

まずは訳を見直した上で、訳註が必要かどうかというのが改めて問われると今のところ考えています。

**Comment by jidaikobo-shibata** [comment]
もんどさん、コメントありがとうございます。
「そもそも原文に忠実な訳出かどうか」については、納得です。

もし、

> 達成基準 1.3.1 により、見出し及びラベルは、プログラムによる解釈がされなければならない。

になるとしても、やっぱり1.3.1は、提供された情報の役割が分け隔てなく伝わることの重要性であって、プログラムでの解釈について強く推奨はされているものの、テキストでもよいということは、書いておいた方が、1.3.1を読む人にとっては、文書間での一貫性があって、安心できるような気がします。

**Comment by bakera** [comment]
WG4で議論し、訳注を付ける方向にしようということになりました。

**Comment by jidaikobo-shibata** [comment]
WG4の皆さんのお時間を使わせて恐縮ですが、でも、ご勘案嬉しいです。

**Comment by momdo** [comment]
要するに、こういうことでしょうか。

訳注案：

上記注釈で「見出し及びラベルは、プログラムによる解釈がされなければならない。」と記述されているが、これは<a href="https://waic.jp/docs/WCAG20/Overview.html#content-structure-separation-programmatic">達成基準 1.3.1</a> を正確に反映したものではない。よって、この記述は達成基準 1.3.1 にあるとおり、「見出し及びラベルは、プログラムで決定できるか又はテキストで利用できなければならない。」と解釈するのが妥当と考えられる。<a href="https://github.com/w3c/wcag/issues/315">w3c/wcag#315</a> で改善が提案されているので、あわせて参照されたい。

 &lt;!-- w3c/wcag # 315 が fix されたら、この訳註を削除すること。 --&gt;

**Comment by jidaikobo-shibata** [comment]
お仕事が丁寧でびつくりしましたよ！？
