### ISSUE TITLE
F65のチェックポイントのolのミス

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag20#133]
現状: https://waic.github.io/wcag20/Techniques/F65.html
原文: https://www.w3.org/TR/WCAG20-TECHS/F65.html

最後の「チェックポイント」で、最初の行をolの項目にしてしまっています。

**Comment by momdo** [comment]
issueありがとうございます。確かにおかしいですね。

<a href="https://github.com/w3c/wcag/blob/df65c93e0a122af5a9aafc1d4b71baf58c0b6b8c/wcag20/sources/techniques/failures/F65.xml#L56">本家のXMLを参考</a>に、
```xml
      <procedure>
         <p>Identify <el>img</el>, <el>area</el> and <el>input</el> elements of type <attval>image</attval>. For each of these elements:</p>
         <olist>
```
WAICのXMLファイルの該当部分（下記）を修正するプルリクエストを作成いただけると助かります！
https://github.com/waic/wcag20/blob/dd04beed231c29ebd636cf55a72ed0989a8dbaa2/wcag20/sources/techniques/failures/F65.xml#L48-L53

**Comment by jidaikobo-shibata** [comment]
ブランチ切ってからのプルリク初めてなので、うまくいっているかどうかわかりませんが、やってみましたー。

**Comment by momdo** [comment]
mergeしたのでissueを閉じます。
