### ISSUE TITLE
zoomとscalingの訳語を検討・統一する

### ISSUE THREAD

**Issue by bakera** [waic/wcag20#138]
https://waic.jp/docs/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html
1.4.4 における"zoom"の訳語に揺れがある。

>if users do not have access to a user agent with zoom support. 
>利用者が、ズームサポートを持つユーザエージェントにアクセスできない場合

>If the author is using a technology whose user agents do not provide zoom support, 
>コンテンツ制作者が、ユーザエージェントによって拡大縮小のサポートを提供していないウェブコンテンツ技術を使用している場合、

また、原文では scaling と zoom が使い分けられているが、どちらも「拡大縮小」となっている。

>The scaling of content is primarily a user agent responsibility. 
>コンテンツを拡大縮小することは、主にユーザエージェントの責任である。

これらの訳し分けと統一を検討したい。
scalingを「拡大縮小」、zoomを「ズーム」とする方針でどうだろうか?

**Comment by momdo** [comment]
> scalingを「拡大縮小」、zoomを「ズーム」とする方針でどうだろうか?

WCAG 2.0本体の<a href="https://waic.jp/docs/WCAG20/Overview.html#larger-scaledef">サイズの大きな (テキスト) (large scale (text))</a>にある注記4で「拡大縮小」としているので、scalingの訳語はこれで確定かと。

訳し分けてよいものかどうか、というところが争点かと思いますが、ウェブブラウザーで「ズーム」という単語は実際に出現しているので、zoomにこの訳語を当てるのは個人的には違和感はありません（ウェブブラウザーでの日英の対比まではちゃんと確認してませんが）

zoom inやzoom outはどう訳すのか（See also: https://github.com/w3c/wcag/search?utf8=%E2%9C%93&q=zoom ）というのも一応確認したいですね（ズームインなのか拡大なのか）

**Comment by bakera** [comment]
では、scalingを「拡大縮小」、zoomを「ズーム」とする方針でいきたいと思います。

**Comment by momdo** [comment]
Wikiより移行
> （WAIC_WG4-455より） 1.4.4などで、既存の訳は「zoom」を「拡大縮小」としているけど、縮小して使う状況はあるのかという疑問。 縮小が稀な例であれば、「拡大」で良いのでは。

**Comment by momdo** [comment]
## zoomの検索結果
https://github.com/w3c/wcag/search?l=XML&p=2&q=zoom

- visual-audio-contrast-scale
- FLASH33
- SCR34 (ok)
- G131 (ok)
- G142 (ok)

## scaleの検索結果
https://github.com/w3c/wcag/search?l=XML&q=scale

- visual-audio-contrast-contrast
- meaning-supplements
- visual-audio-contrast7
- C12
- C14
- C17
- SCR34
- G145
- G146

**Comment by momdo** [comment]
## 縮小の検索結果
- visual-audio-contrast-scale
- visual-audio-contrast-visual-presentation
- G142
- G178
- G146
- G131
- FLASH33
- C17
- SCR34

## ズームの検索結果
- visual-audio-contrast-scale
- G82
- G131
- G142
- FLASH33
- SCR34
