### ISSUE TITLE
「重要な用語」のソート順が原文と異なる

### ISSUE THREAD

**Issue by bakera** [waic/wcag20#139]
PR #129 でのコメントより。

Understandingの各項目の下には「重要な用語」の一覧が現れることがありますが、そのソート順が原文と異なります。ソート順はこのように制御されていて、
````
<xsl:sort data-type="text" select="$gl-src//*[@id = current()/@def]/label"/>
````
参照されているlabelの値は日本語なので、
````
<label> (この文書で用いられている) 支援技術 (assistive technology (as used in this document))</label>
````
日本語の文字コード順でソートされることになっています。
WCAGの用語集自体は原文の順にしている (日本語の五十音順にしたいという意見もあったが、一致規格となる関係上、順番は変更できないということだった) ので、可能であれば原文と同じ順になるようにしたいところではあります。

方法としては、原文を属性か子要素か兄弟要素に入れるなどしてそれでソートされるようにするとか。XMLの構造自体をちょっと変えないとダメではあろうと思います。

**Comment by momdo** [comment]
つまり、この辺が表示部で
https://github.com/waic/wcag20/blob/ec8dcf455cd8af898d3ea04d068a7c3be7f5b657/wcag20/sources/xmlspec-wcag-howto.xsl#L427-L438
実体はここから呼び出していると。
https://github.com/waic/wcag20/blob/25845d2fc028511074f47e74e768a045d4c533dd/wcag20/sources/wcag2-src.REC.xml#L1078-L1088

`<label>` 要素を評価するから日本語順になるわけであって、`<gitem id="">` で評価するようにすればいいのでは。

**Comment by momdo** [comment]
メンテナンスしない方針なのでClose
