### ISSUE TITLE
達成方法集にある地の文の訳注を<trnote>に置き換える

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#151]
下記のような達成方法集の訳注を
http://waic.github.io/wcag20/Techniques/G17.html#G17-tests

https://github.com/waic/wcag20/blob/1a265d5c7cc75ed8f693696c6684b398e3f82499/wcag20/sources/techniques/general/G17.xml#L96

解説書の訳注のように
https://waic.github.io/wcag20/Understanding/navigation-mechanisms-descriptive.html#navigation-mechanisms-descriptive-techniques-head

https://github.com/waic/wcag20/blob/1a265d5c7cc75ed8f693696c6684b398e3f82499/wcag20/sources/understanding/navigation-mechanisms-descriptive.xml#L71-L74

マークアップし直してはどうか。

**Comment by bakera** [comment]
訳注としてマークアップすることに賛成です。

**Comment by momdo** [comment]
達成方法集にあるすべての訳注をG、H、C、F、ARIA別にレビューしました。
- https://gist.github.com/momdo/e018695b972a40c1474921009131d90c
- https://gist.github.com/momdo/b0e68db8a673d51bde4dd86c4e40df7a
- https://gist.github.com/momdo/170b16a9159aef1ed5ae4af81616d5dd
- https://gist.github.com/momdo/e561c237b177ca9d2b8cf965518f8042
- https://gist.github.com/momdo/2bccbe0584d52e3a36f8a1c0d1431dda

**Comment by momdo** [comment]
4月ミーティングで方向性に異論はなかったので、現在の注をレビューの上、マークアップし直す。

**Comment by momdo** [comment]
@bakera gistへのレビューありがとうございました。まとめるとこんな感じでしょうか。
## 委員長に確認
- G21（訳注はイキ）、G57（本文を改訳）
- C22（訳注を改修）

## 訳注を削除
- G14、G17、G18、G145、G146（本文を改訳）
- H24 `ua-issues`、H33 `ua-issues`、H42、H44 `ua-issues`、H56、H69（本文を改訳）、H91（本文を改訳）
- C9、C12 `ua-issues`、C13 `ua-issues`、C14 `ua-issues`
- F49、F65
- ARIA7、ARIA8

## 訳注の補強・修正
- G54、G56、G81、G153、G160、G169
- F22

C22に関しては、1つ目の例が2つ目のコード例の説明に、2つ目の説明が1つ目のコード例の説明に「ひっくり返って」いると思います。
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/C22.html#C22-ex9
http://waic.github.io/wcag20/Techniques/C22.html#C22-ex9

**Comment by bakera** [comment]
ありがとうございます。
C22はそういうことだったんですね。明白な編集ミスの類なので直してしまった上で訳注ですかね。

**Comment by momdo** [comment]
SVR5 が抜けてましたね…これも委員長に確認案件でしょうか？
