### ISSUE TITLE
text alternativeの訳語について

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag20#165]
解説書と達成方法集とで、text alternativeの訳語が「代替テキスト」と「テキストによる代替」のふたつがあてられているようです。原文を読んでもあまり違いがわからないのですが、翻訳の方だと、この使い分けに何か意図があるようにも見受けられます。

「テキストによる代替」は、定義もされているtermなので、もし「代替テキスト」となっている個所が「テキストによる代替」としてよいのでしたら、統一をご検討いただけないでしょうか。

ちなみにWCAG2.0本体では統一されているようでした。

**Comment by bakera** [comment]
text alternativeの訳語は2016年のJIS改正のタイミングで見直された用語の一つです。関連文書には古い訳語が残っている部分がありますが、これは修正が必要と認識しています。
