### ISSUE TITLE
UA Notesに達成基準タイトルの修正を反映する

### ISSUE THREAD

**Issue by bakera** [waic/wcag20#166]
達成基準のタイトルを修正しましたが、UA Notes内ではタイトルを参照するのではなくコピペで持っているため、新タイトルが反映されていません。

例: http://waic.github.io/wcag20/Techniques/ua-notes/flash.html#FLASH8 の「アクセシブルな名前」は「アクセシブルな名前 (accessible name)」となるべき。

面倒ですが手作業で反映する必要があるかもしれません。

**Comment by momdo** [comment]
1月ミーティングで、内容が古いこともあり、訳注で対応することに決定した。

**Comment by momdo** [comment]
訳注案

ユーザーエージェントサポートノートに記載されている内容は古く、また WCAG 2.0 の後続仕様である WCAG 2.1 のサポート文書 Techniques for WCAG 2.1 からは削除されている。そのため、WAIC ではこのページを現在メンテナンスしていない。

**Comment by momdo** [comment]
案2
ユーザーエージェントサポートノートに言及していることをもうちょっと明確に。

ユーザーエージェントサポートノートは記載内容が古く、また WCAG 2.0 の後続仕様である WCAG 2.1 のサポート文書 Techniques for WCAG 2.1 から削除されている。そのため、WAIC ではこのページを現在メンテナンスしていない。

**Comment by bakera** [comment]
ありがとうございます。
どちらの案も問題はないと思いますが、あえて言うと「サポート文書」はWAICでは「関連文書」という呼び方にしていたかなと。
案2のほうが短いので、案2のほうがいいですかね。
