### ISSUE TITLE
video descriptionの訳の訂正（達成基準1.2.1 注記内）

### ISSUE THREAD

**Issue by kentarou-fukuda** [waic/wcag20#171]
https://waic.github.io/wcag20/Understanding/media-equiv-av-only-alt.html

「この達成基準の意図」内の注記にて video descriptionを「映像による説明」と訳しているが、audio descriptionに相当する「音声ガイド」に変更する。

参考： https://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-audio-desc-only.html#top
 audio descriptionの別表記例として video description および descriptive narrationが挙げられている

**Comment by momdo** [comment]
see also: [音声解説 \(audio description\)](https://waic.jp/docs/WCAG20/Overview.html#audiodescdef)
もしかしたら、解説書・達成方法集全般で見直しをした方がよいのかもしれません。

**Comment by kentarou-fukuda** [comment]
すみません、新しいJISでは「音声解説」になっていました。1.2.1の入替は音声解説に変更するようにします。
また、他に用いられている箇所がないかの確認も必要ですね。

**Comment by kentarou-fukuda** [comment]
Googleさん（ https://www.google.co.jp/search?q=%22video+description%22+site:www.w3.org/TR/ ）でざっと確認しましたが、video descriptionは別表記例での利用が中心のようです。

FlashとSilverlightの説明内にも出現しますが、silverlightは翻訳無し、Flashは「音声ガイド」と翻訳済み　でした。

http://www.w3.org/TR/WCAG20-TECHS/silverlight
http://www.w3.org/TR/WCAG-TECHS/flash.html

「音声ガイド」となっている箇所を、一括置換すると良いかもしれません
- ただし、 訳注での利用箇所（例：　『訳注: 日本語では「音声ガイド」とも呼ばれる。』等）を除く

**Comment by bakera** [comment]
どこかのタイミングで全体の見直しをしますが、6月リリースには含めない方向としましす。

**Comment by momdo** [comment]
video description→音声ガイド 自体は福田さんのコミットで完了しているので、issueの当初の目的は一応達成してますね。あとは、
> 「音声ガイド」となっている箇所を、一括置換すると良いかもしれません

と書かれているように、audio description→音声解説 になっているか（音声ガイドになっていないか）を確認すればよいと。
