### ISSUE TITLE
peopleの訳が「人」「利用者」で揺れている

### ISSUE THREAD

**Issue by bakera** [waic/wcag20#176]
https://waic.jp/docs/WCAG20/Overview.html#atdef
>screen readers, which are used by people who are blind to read textual information through synthesized speech or braille;
>text-to-speech software, which is used by some people with cognitive, language, and learning disabilities to convert text into synthetic speech;
>speech recognition software, which may be used by people who have some physical disabilities;

>スクリーンリーダー。全盲の人がテキスト情報を合成音声あるいは点字で読み取るために使用している。
>音声変換ソフトウェア。認知障害、言語障害、及び学習障害のある人が、テキストを合成音声に変換するために使用している。
>音声認識ソフトウェア。何らかの身体障害のある利用者が使用することがある。

peopleが「利用者」だったり「人」だったりしている。「人」で統一する方向としたい。
(※JIS規格票もこのとおりになっているので、次回見直しがあればその際に修正したいところ。)

**Comment by momdo** [comment]
Wikiより移行
> (WAIC_WG4-448より) PeopleとUserがどちらも「利用者」と訳されているが本当にこれで良いのか。 あえて使い分けているのだから、Userはこれまで通り「利用者」、Peopleは「人（々）」と分けるのはどうか。

**Comment by momdo** [comment]
WCAG 2.1で対応するのでClose

**Comment by bakera** [comment]
WCAG 2.2でも対応されていない

https://waic.jp/translations/WCAG22/#dfn-assistive-technologies
>スクリーンリーダー。全盲の人がテキスト情報を合成音声あるいは点字で読み取るために使用している。
>音声変換ソフトウェア。認知障害、言語障害、及び学習障害のある人が、テキストを合成音声に変換するために使用している。
>音声認識ソフトウェア。何らかの身体障害のある利用者が使用することがある。
