### ISSUE TITLE
Procedureの訳語はチェックポイントが妥当でしょうか？

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag20#184]
https://waic.github.io/wcag20/Techniques/G1.html#G1-tests
末尾に「チェックポイント」とありますが、原文はProcedureで、辞書に載っていない訳語ですが、よいのでしょうか？ 「手順」というような方が良いような気がします。

**Comment by bakera** [comment]
「手順」とすることに賛成です。
