### ISSUE TITLE
Activating等に「押下」の訳語が当てられている

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag20#185]
https://waic.github.io/wcag20/Techniques/G1.html#G1-examples
> そのリンクを押下すると、視覚的に

https://www.w3.org/TR/WCAG20-TECHS/G1.html#G1-examples
> Activating the link moves visual focus

Activatingを「押下」と訳すのは変な気がします。そのあとの「Tab キーを押下」は「Pressing tab」は、妥当だと思います。

**Comment by momdo** [comment]
上はG1の事例1に関するものですが、事例2やチェックポイントについてもそれぞれ、
> 利用者は、そのリンクを押下すると、それらのナビゲーション機能をスキップすることができる。
>5. リンクを押下した後、キーボードフォーカスがメインコンテンツへ移動する。

>A user activates the link to skip over the navigation tools.
Check that after activating the link, the keyboard focus has moved to the main content.

という対応になっており、併せて見直しが必要でしょう。

**Comment by momdo** [comment]
「押下」で達成基準を調べたものです。
## G70
https://waic.github.io/wcag20/Techniques/G70.html#G70-ex2
> リンクを押下するとオンライン辞書が新しいウィンドウで開き、単語とその定義が表示される。

https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G70.html#G70-ex2
>Activating a link will open up a new window to an online dictionary site with the specific vocabulary word defined.

## G155
https://waic.github.io/wcag20/Techniques/G155.html#G155-description
>処理を続行するために利用者はチェックボックスの選択と送信ボタンの押下の両方をしなければならず、結果として入力内容をサイド確認することにつながる。

https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G155.html#G155-description
>Providing the checkbox as a separate control from the submit button forces the user to "double-check", as they must both select the checkbox and activate the submit button for the transaction to proceed.

## G201
https://waic.github.io/wcag20/Techniques/G201.html#G201-description
> リンクを押下したときに自動的に新しいウィンドウを開くことは、もし事前にそのことを知らせていなければ、視覚的なコンテンツを知覚するのに困難を伴う利用者や認知障害のある利用者が混乱する原因となりうる。

https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G201.html#G201-description
> Opening new windows automatically when a link is activated can be disorienting for people who have difficulty perceiving visual content, and for some people with cognitive disabilities, if they are not warned in advance. 

## G202
https://waic.github.io/wcag20/Techniques/G202.html#G202-description
> たとえ使用している計算装置がハードウェアのキーボードを含んでいない場合も、キーボードインタフェースが利用者にキーの押下によるプログラムへのインプットを許容する。

https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G202.html#G202-description
> A keyboard interface allows users to provide keystroke input to programs even if the computing device that they are using does not contain a hardware keyboard. 

## FLASH19
See also https://github.com/waic/wcag20/issues/189#issue-328717938
https://waic.github.io/wcag20/Techniques/FLASH19.html#FLASH19-examples
> 利用者は、所定の 20 秒で、スペースバーを押すか、「はい」ボタンを押下する。

https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/FLASH19.html#FLASH19-examples
> The user is given 20 seconds to press the space bar or click on the "Yes" button.

## SCR20
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/SCR20.html#SCR20-ex2
> キーボードのキー押下が Enter キーであるかどうかをチェックしていることに注目してほしい。もしチェックしなければ、画像にフォーカスがあるときには、どのキーが押下されても常に反応してしまうため望ましくない。
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/SCR20.html#SCR20-ex2
> Note that in this example, the nextPage() function should check that the keyboard key pressed was Enter, otherwise it will respond to all keyboard actions while the image has focus, which is not the desired behavior.

## SCR29 (OK)
https://waic.github.io/wcag20/Techniques/SCR29.html#SCR29-examples
> onkeyup ハンドラはエンターキーが押下された際、アクションを実行する。
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/SCR29.html#SCR29-examples
> The onkeyup handler will invoke the action when the Enter key is pressed. 

## SCR37
https://waic.github.io/wcag20/Techniques/SCR37.html#SCR37-tests
> Tab キーでその場所に移動して Enter キーを押下することで、ダイアログを開くことができる。
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/SCR37.html#SCR37-tests
> Check that the dialogs can be opened by tabbing to the area and hitting enter.

## PDF7
https://waic.github.io/wcag20/Techniques/PDF7.html#PDF7-examples
> 3. 次のダイアログボックスで、「ページ」(1 ページのみ変換する場合は「現在のページ」) の下の「すべてのページ」ラジオボタンを選択し、［OK］を押下する

https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/PDF7.html#PDF7-examples
> 3. In the next dialog, select the All Pages radio button under Pages (or Current Page if you are converting only one page), and then select OK.

## PDF9
https://waic.github.io/wcag20/Techniques/PDF9.html#PDF9-ex3
> 3 「タグ付き PDF」を選択して、［エクスポート］を押下する

https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/PDF9.html#PDF9-ex3
> 3 Select Tagged PDF, then select Export.

## PDF15
https://waic.github.io/wcag20/Techniques/PDF15.html#PDF15-ex1
5の最後
> ［追加］を押下する
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/PDF15.html#PDF15-ex1
> Click Add.

## PDF17
https://waic.github.io/wcag20/Techniques/PDF17.html#PDF17-ex1
> 4. ［OK］を押下する

https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/PDF17.html#PDF17-ex1
> 4. Select OK

## PDF19
https://waic.github.io/wcag20/Techniques/PDF19.html#PDF19-ex1
> 3. TouchUp 読み上げ順序ツールの［順序パネルを表示］ボタンを押下する

https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/PDF19.html#PDF19-ex1
> 3. Click the Show Order Panel button in the TouchUp Reading Order Tool

## PDF22
https://waic.github.io/wcag20/Techniques/PDF22.html#PDF22-ex2
> 2. ［オブジェクト］パレットで、［検証パターン］ボタンを押下する

https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/PDF22.html#PDF22-ex2
> 2. In the Object palette, click the Validation Pattern... button.

**Comment by momdo** [comment]
同様に解説書についても列挙してみます

## 2.2.2 を理解する
https://waic.github.io/wcag20/Understanding/time-limits-pause.html#time-limits-pause-examples-head

https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/time-limits-pause.html#time-limits-pause-examples-head
>A form prompt
A form blinks an arrow near the submit button if a user finishes filling out the form but does not activate the submit button. 

## 2.4.3 を理解する
https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/navigation-mechanisms-focus-order.html
第3段落
> 右向き矢印キーを押下するとノードを展開して、それから下向き矢印キーを押下すると新しく展開されたノードへと移動していく。

> Pressing the right arrow key may expand a node, then using the down arrow key, will move into the newly expanded nodes.

具体的なメリット:
>字を読むのが困難な障害のある利用者は、Tab キーを押下してフォーカスが予期しないどこかへ移動してしまうと、迷子のようになってしまう恐れがある。彼らは論理的なフォーカス順序の恩恵を受けている。
視覚障害のある利用者は、Tab キーを押下してフォーカスが予期しないどこかへ移動してしまったり、インタラクティブな要素に囲まれているコンテンツを容易に見つけることができなかったりすると、迷子のようになってしまう恐れがある。

> People with disabilities that make reading difficult can become disoriented when tabbing takes focus someplace unexpected. They benefit from a logical focus order.
People with visual impairments can become disoriented when tabbing takes focus someplace unexpected or when they cannot easily find the content surrounding an interactive element.

達成基準 2.4.3 の事例
>インタラクティブなコントロールのツリーがあるウェブページ上で、利用者は上下の矢印キーを使って、ツリーのノードからノードへと移動することができる。右向き矢印キーを押下するとノードを展開して、それから下矢印キーを押下すると新しく展開されたノードへと移動していく。
あるウェブページは、スクリプトでモードレスダイアログを実装している。起動ボタンを押下すると、ダイアログが開く。ダイアログ内にあるインタラクティブな要素が、起動ボタンのすぐ後のフォーカス順序の位置に挿入される。ダイアログが開いているときには、フォーカス順序は、その起動ボタンからダイアログ内の要素へ移動し、それから起動ボタンの後にあるインタラクティブな要素へと移動する。ダイアログが閉じているときは、フォーカス順序は起動ボタンからその次に続いている要素へ移動する。
あるウェブページは、スクリプトでモーダルダイアログを実装している。起動ボタンを押下すると、ダイアログが開き、そのダイアログにある最初のインタラクティブな要素にフォーカスがあたる。ダイアログが開いている限り、フォーカスはダイアログ内の要素だけに限定される。ダイアログが閉じられると、フォーカスはボタン又はボタンの次にある要素へ戻る。

>On a web page that contains a tree of interactive controls, the user can use the up and down arrow keys to move from tree node to tree node. Pressing the right arrow key expands a node, then using the down arrow key moves into the newly expanded nodes.
A Web page implements modeless dialogs via scripting. When the trigger button is activated, a dialog opens. The interactive elements in the dialog are inserted in the focus order immediately after the button. When the dialog is open, the focus order goes from the button to the elements of the dialog, then to the interactive element following the button. When the dialog is closed, the focus order goes from the button to the following element.
A Web page implements modal dialogs via scripting. When the trigger button is activated, a dialog opens and focus is set to the first interactive element in the dialog. As long as the dialog is open, focus is limited to the elements of the dialog. When the dialog is dismissed, focus returns to the button or the element following the button.

## 3.2.2 を理解する
https://waic.github.io/wcag20/Understanding/consistent-behavior-unpredictable-change.html#consistent-behavior-unpredictable-change-intent-head
> つまり、チェックボックスを選択する、テキストフィールドにテキストを入力する、又はリストコントロールのオプションを選択すると、コンポーネントの設定を変更するが、リンク又はボタンを押下したときはそうはならない。
https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/consistent-behavior-unpredictable-change.html#consistent-behavior-unpredictable-change-intent-head
> So checking a checkbox, entering text into a text field, or changing the selected option in a list control changes its setting, but activating a link or a button does not.

**Comment by bakera** [comment]
activateの訳については本体側で議論した記憶があります。
https://waic.jp/docs/WCAG20/Overview.html#ambiguouslinkdef などを見ると「動作させる」としたようです。

**Comment by momdo** [comment]
個人的には「動作させる」よりかは「作動させる」のほうがしっくりきますが、「動作させる」が誤りとまではいえないので、一旦「動作させる」にあわせてみますか。（以下辞書類）

- https://ejje.weblio.jp/content/Activate
- https://eow.alc.co.jp/search?q=Activate
- https://dictionary.goo.ne.jp/jn/155710/meaning/m0u/
- https://dictionary.goo.ne.jp/jn/88647/meaning/m0u/
