### ISSUE TITLE
ドラッグアンドドロップとドラッグ＆ドロップの混在

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag20#186]
以下のように表記揺れしています。

■ドラッグアンドドロップ
https://waic.github.io/wcag20/Techniques/wai-aria_notes.html
原文 drag-and-drop
https://waic.github.io/wcag20/Techniques/SCR27.html
原文 drag and drop
https://waic.github.io/wcag20/Techniques/G90.html
原文 drag and drop

■ドラッグ＆ドロップ
https://waic.github.io/wcag20/Techniques/G202.html
原文 drag and drop
https://waic.github.io/wcag20/Techniques/PDF3.html
原文 Drag-and-drop

**Comment by bakera** [comment]
WG4ミーティングでは、&を使用した表記のほうがカタカナが連続しないため読みやすいのではないかという意見が出ました。また、このほかに「&」「アンド」が使用されている個所を調査したほうがよいのではという意見が出ました。

**Comment by jidaikobo-shibata** [comment]
言われてみると「ドラッグ＆ドロップ」の方が視認性は良さそうですね。

**Comment by momdo** [comment]
全角アンパサンドは次の1点のみ。
https://waic.jp/docs/UNDERSTANDING-WCAG20/conformance.html#uc-levels-head
> その達成基準が、「ルック＆フィール」及び／又はウェブページの機能に制限

**Comment by momdo** [comment]
https://waic.jp/docs/UNDERSTANDING-WCAG20/keyboard-operation-keyboard-operable.html#keyboard-operation-keyboard-operable-examples-head

> 達成基準 2.1.1 の事例 
> 事例 2: ドラッグアンドドロップ機能
