### ISSUE TITLE
アラビア数字と漢数字の表記の不統一

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag20#187]
「1 つ」「一つ」の表記揺れが多く、気になります。
それぞれ多数あるので、例示しません。

以下のような表記揺れもありました。

三次元
G160.xml

二次元
H51.xml

2 次元
F49.xml
G82.xml
PDF6.xml
SCR27.xml

**Comment by bakera** [comment]
気にはなるものの、意図が誤解されるといったクリティカルな問題でもなく、すべてを対応しようとすると作業量が多いという問題もあり、いったん優先度低めで考えたいと思います。
ガイドラインを策定したのち、ガイドラインに反すると指摘された部分を修正するという方針にしたいと思います。
