### ISSUE TITLE
conformance.htmlの<title>が不適当

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag20#188]
https://waic.github.io/wcag20/Understanding/conformance.html
titleが「WCAG 2.0 への適合を理解する を理解する」となっています。
原文は

> Understanding Conformance

です。

**Comment by momdo** [comment]
https://github.com/waic/wcag20/blob/5d4849871ddcd7c127461a67340e515eae6dbd8d/wcag20/sources/slices-understanding-common.xsl#L105-L109
この部分に関して、「を理解する」を`xsl:if`で分岐させれば解決できそうですね
