### ISSUE TITLE
コラムとカラムを訳し分けてはどうか

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#193]
Per https://github.com/debiru/wcag20/commit/ccf77dc152693f671b0f54185bc0a7e4aacaa611

**Comment by bakera** [comment]
「コラムの見出し」だとコラムニストが書いている文章に見出しがついている話のように思える、ということでしょうか。 https://ja.wikipedia.org/wiki/コラム を参考に使い分けを考えても良い (そうするのであればたいてい「カラム」表記になるはず) という意見も。

**Comment by bakera** [comment]
結論としては、指摘されている部分はすべて「カラム」で良いのではないか。
