### ISSUE TITLE
達成方法集のクオリティレビューの可能性について

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#194]
Per https://github.com/debiru/wcag20/issues/2
> - 元の翻訳作業者が（精度の低い）機械翻訳で済ませているような箇所については、翻訳文を改善する必要性が低いと思われる（というか自然な日本語を提案するのに時間がかかる）
> - 「適用」とすべきところで「適応」と書いている箇所が見受けられるが、その文章を修正しようと思ったものの、その前後あるいは段落そのものの翻訳精度が低い
> - どこまでレビュー（修正の提案）をするべきかよくわからなくなってきた

これまで、解説書に関してUnderstandingクオリティーレビューと称して見直しを一通り行ったが、達成方法集に関しても同様の作業を行った方がよいかもしれない。

とはいっても、Understandingクオリティーレビューについては見直しの基準が曖昧な側面もあったので、作業者によってレビューの度合いがまちまちであり、なおも品質にバラツキがある。

達成方法集は数が多いこと、WG4でATAG 2.0やWCAG 2.1の訳出作業を行っているので、このリポジトリにつきっきりというわけにもいかない（かといって、何もしないのも好ましいとは思わない）。

どのように翻訳品質を持続的に向上させるかの方策の検討が必要だろう。

**Comment by bakera** [comment]
やみくもにレビューをするのではなく、向上の方策を検討したい。持続的に向上というからには「向上している」ということを確認する必要もあり、効果測定の手段を検討する必要もあるのではないか、という意見が出た。

**Comment by momdo** [comment]
そこまでやるリソースがWG4に現存しないので、一旦閉じる。
