### ISSUE TITLE
Wiki「用語・用字」についてを移行する

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#196]
[用語・用字について](https://github.com/waic/wcag20/wiki/%E7%94%A8%E8%AA%9E%E3%83%BB%E7%94%A8%E5%AD%97%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)を[waic/translation\_guidelines](https://github.com/waic/translation_guidelines)に移行させる。

- [x]  [WAIC\-wcag20\-trans\-guide\.md](https://github.com/waic/translation_guidelines/blob/master/WAIC-wcag20-trans-guide.md)と明らかに重複するものを削除
- [x]  ページ内コンテンツをまとめ直す
- [ ] レポジトリを移管
- [ ]  新しいURLのみとするか、Wikiページごと削除する。

の手順で行う。

**Comment by bakera** [comment]
スプレッドシートに移植する方向で。

**Comment by bakera** [comment]
スプレッドシートはこちら。
https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0

**Comment by momdo** [comment]
スプレッドシートを活用できているのかはさておき、移行はしているのでClose
