### ISSUE TITLE
WCAG 2.0 解説書の「」有り／無しの揺れ

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag20#207]
https://waic.github.io/wcag20/Understanding/intro.html

h1見出しが「」無しなのに本文では「」有りになっています。

**Comment by momdo** [comment]
https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/intro.html
イントロダクションにおけて、不要なかぎ括弧（原文でダブルクオーテーションのないもの）はすべて除去する
