### ISSUE TITLE
イントロダクション 文章の重複

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag20#208]
https://waic.github.io/wcag20/Understanding/intro.html

3段落目で下記文章が2回繰り返されています。（これは現行の公開ページもでしたね...orz

「ガイドライン X.X を理解するという節がある。そのガイドラインの意図が説明されているほか、達成方法の中でも、そのガイドラインには関係あるが特定の達成基準には関係のない達成方法が、そこに列挙されている。」

**Comment by momdo** [comment]
該当箇所（ソース）
https://github.com/waic/wcag20/blob/c06100df0b0f81dce021202ce7a3cfa3f916f579/wcag20/sources/guide-to-wcag2-src.xml#L130
原文
https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/intro.html
> Understanding WCAG 2.0 is organized by guideline. There is an Understanding Guideline X.X section for each guideline. The intent and any advisory techniques that are related to the guideline but not specifically related to any of its Success Criteria are listed there as well.

原文と比較するとやや誤訳気味か。

**Comment by momdo** [comment]
そのガイドラインの意図と、ガイドラインに関係あるが、そのガイドラインの達成基準のいずれにも特に関係のない参考達成方法も同様にそこに列挙されている。

ぐらいでどうか。
