### ISSUE TITLE
「ガイドライン 1.3 を理解する」で気になるところ

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag20#214]
https://waic.github.io/wcag20/Understanding/content-structure-separation.html

> 構造: ウェブページの構成要素が相互に関係して系統的に整理されている状態で、かつウェブページの集合が整理されている状態。

> structure: the way the parts of a Web page are organized in relation to each other; and the way a collection of Web pages is organized

wayが「状態」なのが気になります。
また、organizedが「系統的に整理されて」というのも気になります。
andもこの場合「かつ」でしょうか？

これもやや意訳ですが、前掲の文章を受けての「構造」を説明するとしたら、以下のような形ではどうでしょうか？

> 構造: ウェブページの各部分のそれぞれの関係においての組織のされかたや、ウェブページの集合の組織のされかた。

あと瑣末ですが、次項の「表現」の前に半角スペースがあります（ちなみに原文も）。でも、ソースコードでは見つけられなくてプルリクできませんでした。

**Comment by momdo** [comment]
> あと瑣末ですが、次項の「表現」の前に半角スペースがあります（ちなみに原文も）。でも、ソースコードでは見つけられなくてプルリクできませんでした。

UAによって、スペースがあったりなかったりするように見えるだけかと。

**Comment by momdo** [comment]
案：
構造: ウェブページの各部分が互いに関してどのように組織されるか、及びウェブページの集合がどのように組織されるか。

**Comment by momdo** [comment]
from https://github.com/waic/translation_guidelines/issues/29:
原文：
> (visually, audibly, tactilely etc.)

現行訳：
>(視覚的、聴覚的、触覚的、又はその他の方法で)

提案：
(視覚的、聴覚的、触覚的など)

**Comment by momdo** [comment]
全般的におかしいのでレビューの必要あり。
