### ISSUE TITLE
「リニアライズ」と「線形」の揺れ

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag20#215]
基本的には「リニアライズ」と訳出されているようですが、ところどころ「線形」となっています。

そもそも「リニアライズ」は、わかりやすい翻訳なのか悩ましい気がします。「線形化」がわかりやすいかどうかもわかりませんが、Googleの検索結果数（これを判断基準にすべきかわかりませんが）では、「線形化」のほうが多いようです（ただ個人的には「リニアライズ」のほうが読みやすいです）。

以下、「線形」を抽出した箇所です。

minimize-error-cues.xml:79

> 線形なフォームのデザインを提供

content-structure-separation-sequence.xml:16

> 特定の線形順序を提供することが要求されるのは、意味に影響を与えるときだけである。

content-structure-separation-sequence.xml:66

> 線形化された描画のリンクを提供する (リンク追加予定)

navigation-mechanisms.xml:9

> スクリーンリーダーは、コンテンツを合成音声に変換するが、それは音声なので、合成音声は線形順序で提示されなければならない。

以下はRGBの値の話のようですが、妥当性がよくわかりません。

visual-audio-contrast7.xml:43

> RGB 値の非線形から線形への変換は、IEC/4WD 61966-2-1 <bibref ref="IEC-4WD"/> 及び "A Standard Default Color Space for the Internet - sRGB" <bibref ref="sRGB"/> に基づいている。

visual-audio-contrast-contrast.xml54

> RGB 値の非線形から線形への変換は、IEC/4WD 61966-2-1 <bibref ref="IEC-4WD"/> 及び "A Standard Default Color Space for the Internet - sRGB" <bibref ref="sRGB"/> に基づいている。

あと、

https://waic.jp/docs/WCAG-TECHS/F34

では、linearlyに対して、「直線的」という訳語をあてているようです。

**Comment by momdo** [comment]
リニアライズと訳されている箇所の全部列挙といかないまでにしても、例示は欲しかったような。

**Comment by bakera** [comment]
F49には「線形化 (リニアライズ)」という表記もあります。
https://waic.jp/docs/WCAG-TECHS/F49.html

リニアライズが分かる人は線形もわかるのではないか、という意見がありました。
全部「線形化 (リニアライズ)」で統一するという選択肢もありますが、それはそれでうるさいかも。

**Comment by jidaikobo-shibata** [comment]
> 少なくとも、RGB値の話は数学用語で言うところの非線形か線形という話なので、現行の対応訳語がおかしいとは思いません。（訳出がこれでいいのかという話は別にして）
RGBに関しては、あまり異論はありません。

> リニアライズが分かる人は線形もわかるのではないか、という意見がありました。
それはそうでしょうね。

「線形なフォームのデザイン」とか「線形順序」って、初学者にはわかりづらいような気がしての問題提起でしたが、むしろ訳語の問題ではないのかもしれません（代案がありませんが）。

**Comment by momdo** [comment]
「線形順序」はわかりにくいというコメントがあった（https://github.com/waic/wcag20/issues/169#issuecomment-397587031 ）ので、https://github.com/waic/wcag20/pull/266/commits/76a75c51c201317fef020b030d27c25794284178 では
> 合成音声は直線状の順番で提示されなければならない。

としました。

**Comment by bakera** [comment]
「直線状の順番」は何を言っているのか分かりにくく、「線形順序」のほうがまだわかりやすいという印象です。
線形順序のままにして訳注というのもありではないでしょうか?

**Comment by momdo** [comment]
@jidaikobo-shibata 
で、これは結局どうすればいいんですかね…？（このissueを見ても話の趣旨を思い出せない的な）

**Comment by jidaikobo-shibata** [comment]
なるほど。落ち着いて見てみると、たしかに「直線上の順番」より、「線形順序」のほうがわかりやすいですね。

そもそもの問題提起は、レビュー時に、「気になったことはとりあえずissueを立てる」というメンタリティで立てたissueですので、「リニアライズ」と「線形」の表記揺れは、とくに問題ではない（誰も困らない）ということでしたら、closeしてもらって良いと思います。

**Comment by momdo** [comment]
@jidaikobo-shibata
> とくに問題ではない（誰も困らない）

ということはないと思いますが、このままだと、「線形（化）」と「リニアライズ」を全部日本語を列挙した上で、しかも英語の単語と比較しつつ、どう統一するのか（もしくはそのままにするのか）を考えないといけない（しかも、RGB値に関しては、これ以外の用語統一にかかわらず、独立して扱う必要がある）ので、何か腹案なり（方針なり）があると嬉しい、という話ですね。

**Comment by momdo** [comment]
線形化のほうがGoogleの検索結果が多そうなので、線形化に統一してみます。
