### ISSUE TITLE
達成方法タイトルにおける presentation の使い分けについて

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag20#220]
presentation の訳が使い分けられていますが、どこまで意図的なものなのか分かりませんでしたのでピックアップしておきますが、全部意図的だったらごめんなさい。

- presentation：提示／表現の混在

原文：G140: Separating information and structure from presentation to enable different presentations
↓
旧訳：G140: 情報と構造を表現から分離して、異なる表現を可能にする
↓
新訳：G140: 異なる提示を可能にするために、情報と構造を表現から分離する

- presentation：表示

原文：C15: Using CSS to change the presentation of a user interface component when it receives focus
↓
旧訳：C15: ユーザインタフェースコンポーネントがフォーカスを受けとったときの表示を変更するために、CSSを使用する
↓
新訳：C15: ユーザインタフェースコンポーネントがフォーカスを受けとったときの表示を変更するために、CSS を使用する

- presentation：見栄え

原文：F2: Failure of Success Criterion 1.3.1 due to using changes in text presentation to convey information without using the appropriate markup or text
↓
旧訳：F2: 達成基準 1.3.1 の失敗例 － 適切なマークアップ又はテキストを用いずに、テキストの見た目の表現の変化を用いて情報を伝えている
↓
新訳：F2: 達成基準 1.3.1 の失敗例 － 情報を伝えるために、適切なマークアップ又はテキストを用いずに、テキストの見栄えの変化を使用している

**Comment by momdo** [comment]
#33 も参照。

**Comment by SawadaStdDesign** [comment]
#33 は以前目を通していたので、その上で上記指摘箇所がこうなっているのはどういう意図なんだろうと思ったわけです。
が、まだ #33 はまだ close してなかったんですね...
