### ISSUE TITLE
達成方法集 冒頭 リンクテキストの下線なし

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag20#222]
https://waic.github.io/wcag20/Techniques/Overview.html

「過去の編集者:」一覧下の文中リンクテキスト「Alternate Versions of Web Content Accessibility Guidelines 2.0」に下線が引かれていません。

**Comment by momdo** [comment]
原文から変更して`<p>`にしているのが原因なので、これを解消するには原文にあわせて（1項目だけにもかかわらず）`<ul>`に戻すのが一番早そうです。
