### ISSUE TITLE
1.4.3のCSS Valuesのリンク切れ

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag20#269]
`<loc ref="https://www.w3.org/TR/css3-values/#absolute-lengths">CSS3 Values</loc>`
が二箇所ありますが、リンクが切れています（`h`が足らない？）。

原文でも切れているので、あちらにもissueを立てています。
https://github.com/w3c/wcag/issues/475

**Comment by momdo** [comment]
@jidaikobo-shibata 
`<loc href>`が正しいですね。PRお待ちしております。
