### ISSUE TITLE
キー表記が揺れている

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#272]
WAICメーリングリスト投稿（waic-all:00280 @SawadaStdDesignさん）より

> > WCAGは「タブキー」「エンターキー」「スペースキー」のようです。
> 
> ちなみにWCAGをwaicサイト内でざっと見たところ、
> 
> 「Tab キー」
> 2.1.2
> 2.4.3 解説書
> G1／G21／G59／G83／SCR20／SCR37／FLASH15／FLASH17／PDF3／F10／F44／F84
> 
> 「タブキー」「タブ移動」「タブ順序」
> 2.1.2 解説書／2.4.3 解説書
> G21／G57／G59／G71／G107／G165／G170／G183／G195／H4／H51／H65／C15／SCR21／SCR26／SCR29／SCR31／SCR37／T1／T3／ARIA9／ARIA11／ARIA18／Flashテクノロジーノート／FLASH1／FLASH2／FLASH6／FLASH11／FLASH15／FLASH17／FLASH18／FLASH22／FLASH28／PDF1／PDF3／PDF10／PDF11／PDF15／PDF23／F32／F33／F34／F36／F42／F44／F48／F85
> 
> 「Enter キー」
> SCR20／SCR29／SCR35／FLASH14／PDF11／F36／F42
> 
> 「エンターキー」
> G60／SCR29
> 
> 「Space キー」
> なし
> 
> 「スペースキー」
> 2.1.1 解説書
> G4／SCR35／FLASH16
> 
> 現状公開されているものは、バラバラでしたね...
> バラバラであまり参考にならなかったので、WG4 の翻訳方針に合わせるという形でも良いのかなと思います。

Related #189

少なくともWAICサイトではキーの表記が英語とカタカナで揺れている。GitHub Pagesおよび原語は未確認。

**Comment by bakera** [comment]
Tabキーに関してはJIS原案作成委員の中で議論があって、キートップに「タブ」ではなく「Tab」と刻印されていることがほとんどなので「Tab」キー、スペースは「Space」という刻印があるわけではないので「スペースキー」としたように記憶しています。

**Comment by bakera** [comment]
こういう理由なので、「タブパネル」みたいなものはカタカナの「タブ」になっていますね。

**Comment by jidaikobo-shibata** [comment]
Windowsのキーボードでもおそらく、すべてが「Tab」「Enter」となっているわけでもないと思うので、「とあるキーボードのキートップが『Tab』『Enter』なので」という理由に受け取られかねない気がします。

ちなみにMacのデフォルトのキートップは「tab」「return」とすべて小文字で、純正のフルキーボードのテンキー部分に「enter」があります（MacBookだと「enter キー」は存在しない）。

検索するときに、「Tabキー」「Tab キー」みたいな表記揺れが起こり得ますし、全部カタカナにしちゃうのが、ベターな気がします（「タブキー」を検索したい場面はたくさんあると思うので）。

**Comment by momdo** [comment]
キー刻印は特段の事情がない限り、109キーボードを念頭に置けば良いのではないかなと。
参考：[キー配列 - Wikipedia](https://ja.wikipedia.org/wiki/%E3%82%AD%E3%83%BC%E9%85%8D%E5%88%97)
