### ISSUE TITLE
ARIA7: 「指定された動作」という訳を見直したい

### ISSUE THREAD

**Issue by bakera** [waic/wcag20#299]
https://waic.github.io/wcag20/Techniques/ARIA7.html

>aria-labelledby の指定された動作は、
>The specified behavior of aria-labelledby is that 

誰がどこで指定しているのか謎な感じがします。
この specified は要は spec で決められているという話なので、「仕様上の」とか「仕様で定義された」くらいの訳の方が良いかもしれません。

**Comment by momdo** [comment]
@bakera よく見たら、specifyってspecificationの動詞形ですね…「仕様上の」で良いのではないでしょうか。
