### ISSUE TITLE
H70: AS情報へのリンク切れ

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag20#306]
https://waic.github.io/wcag20/Techniques/H70.html

の訳注「2014 年 6 月版のアクセシビリティ・サポーテッド（AS）情報: H70-1」は、リンク切れしています。

以下リンクであればつながります。

https://waic.jp/docs/as/info/201406/H70.html

だと思いますので、「H70-1」とあわせてリンク先を直して良いと思います。

なお、「H70-1」という書き方が気になったので、旧サイトのdocsを確認してみましたが、それも存在しないようでした。「本当は、ASに『H70-1』があるのだ」という場合は、そちらを修正すべきかもしれません。

**Comment by momdo** [comment]
単に「H70-1」というファイルがあると誤認してただけかと思います。
