### ISSUE TITLE
翻訳コメント受付フォームへのリンクを検討

### ISSUE THREAD

**Issue by bakera** [waic/wcag20#319]
翻訳コメント受付フォームを、ひとまずGoogle formで用意した。
翻訳文書の各ページから「お問い合わせ」リンクを押したとき、対象URLがフィルされた状態でフォームが開くようになっていると望ましい。

たとえば以下のようなURLでリクエストするとフィルされる。

https://docs.google.com/forms/d/e/1FAIpQLSdIpvogLx8kGIMewhQ6MzhG2pOCQZ50iIBViGg8pUrRJuslKg/viewform?entry.685195438=https://waic.jp

このようなクエリを含むリンクが、JavaScript等で自動で生成されると良いと思われる。

**Comment by bakera** [comment]
願望としては、WCAGとかATAGとかいろいろなタイプのHTMLに対して共通で使えるものにしたいと思いますので、外部JSファイルにしておいて、script要素で呼ぶだけで完結すると美しいかもしれませぬ。
冒頭訳注っぽい箇所に自動でリンクを追加するという挙動でも良いかも?

あと、window.location.href の値をそのまま使うと、意図しない動作になることがありそうな気がします。DOM操作でsetAttributeしているのでXSSにはならないと思いますが、値自体に & などが含まれていた時にパラメータが追加できてしまったりとか。

**Comment by momdo** [comment]
>願望としては、WCAGとかATAGとかいろいろなタイプのHTMLに対して共通で使えるものにしたいと思いますので、外部JSファイルにしておいて、script要素で呼ぶだけで完結すると美しいかもしれませぬ。

そうですね。その方がよさそうではあります（とりあえず動くものを貼り付けたかったという意図です）。

> 冒頭訳注っぽい箇所に自動でリンクを追加するという挙動でも良いかも?

なるほど。作ったときのイメージとしては、解説書や達成方法集の個別ページを想定していました。

> あと、window.location.href の値をそのまま使うと、意図しない動作になることがありそうな気がします。
```javascript
let viewurl = encodeURIComponent(window.location.href);
```
こうすれば安全ですかね…？

**Comment by momdo** [comment]
> 冒頭訳注っぽい箇所に自動でリンクを追加するという挙動でも良いかも?

それはそれとして1月ミーティングで出ていたように、翻訳に関する問い合わせのメールアドレスがなくなっているので、各所の訳注を修正した方がいいかもしれませんね。

**Comment by jidaikobo-shibata** [comment]
Google Formでことたりるかもしれませんが、場合によると、WAICサイトにそういった仕様のフォームを作ることも技術的には可能ですので、いちおうお伝えまで。

**Comment by jidaikobo-shibata** [comment]
気軽に送信できるのは良いと思いますし、とっても匿名性の高い仕様なのも、これはこれでアリの方針だと思いますが、「コメントの意図を計りかねる時、コメント主に尋ねたい」というような運用は難しそうですね。

**Comment by momdo** [comment]
>「コメントの意図を計りかねる時、コメント主に尋ねたい」

解釈が難しいコメントが来るなら来るでいいのかなあと。それ以前にコメントの絶対量を増やしたい（と少なくとも私は思っている）ので、入力項目は少ない方が気楽かなと。

**Comment by momdo** [comment]
@bakera https://github.com/waic/translation_guidelines/pull/40 にjsのPull Requestを作成しました。

**Comment by MasaoYOMODA** [comment]
@momdo @bakera @jidaikobo-shibata ... 今更、ですが この closed issueを WG1のセミナーリーダーにも紹介させてくださいね。

**Comment by momdo** [comment]
@MasaoYOMODA むしろ宣伝していただければと…！🙇
