### ISSUE TITLE
サーバvsサーバー

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#325]
長音ありなしが混ざっている。

ex https://waic.github.io/wcag20/Techniques/F40.html#F40-related-techs
> しかしながら、これを実行するためにはサーバーサイドの達成方法を用いることが望ましい。SVR1: クライアントサイドではなく、サーバサイドで自動リダイレクトを実装する (SERVER) を参照のこと。

**Comment by bakera** [comment]
WCAG 2.0本体では「サーバ」「サーバー」いずれも使用されていない模様。
「ユーザー」ではなく「ユーザ」を採用しているので、その伝でいけば「サーバ」のほうになりますね。

**Comment by momdo** [comment]
ヘッダー・フッターの話（#93）を思い出しましたが、結構混沌としていますね…

**Comment by momdo** [comment]
進展がないので、何かコメントがあればいただければと…！ @caztcha

**Comment by caztcha** [comment]
http://www.yamanouchi-yri.com/yrihp/techwrt-2-4s/t-2-4s07a-1.htm

> カタカナ表記の際に「つづりの終わりの-er、-or、-arあるいは-y」に対応して語尾の音に長音記号を付けるのが原則です。これに対し、技術分野によっては長音記号を省く慣例があります。

個人的には、語尾が er や or で終わる単語には何も考えずに長音を付けたい派ですが、server を「技術分野 (のことば)」と捉えて「サーバ」と表記するのは、ありかもですね。

**Comment by momdo** [comment]
コメントありがとうございます…！

伝統的な（？）技術用語に寄せるなら長音を省く、発音にあわせる格好にするなら長音を付けるという感じでしょうか。

> ただ、現状、WCAG 日本語訳を見てみると、長音記号で終わる表記もあるので (ディレクター、レイヤー、ウェブデザイナー ...)、https://github.com/waic/wcag20/issues/93#issuecomment-384527152 を踏襲して、とりあえず user 以外は長音記号を付ける、というのがよいのかな、という気がします。

WCAG 2.0にないもので、付けて構わないものは付けるのがおさまりがいい気はしますね。いかがでしょう？ @bakera

**Comment by bakera** [comment]
じゃあ伸ばしましょう。
