### ISSUE TITLE
presentationの訳出の確認

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#33]
Backlog WAIC_WG4-464より。

https://github.com/waic/wcag20/commit/1daa8d1577694adfbcda1957ed1309f534e4cf5d でのG117の訳出追加により、"the variation in presentation of text" の訳に関して、「テキストの提示によるバリエーション」ではなく、「テキストの**表現**のバリエーション」と最終的にした、  @kentarou-fukuda さんからの以下のコメント。

>G117の見出しの「表現」を「提示」に直した理由が、（WCAG 2.0）本体側で「提示」とされていることだったのですが、現状では、G117内ではpresentationを提示と訳している箇所はない（今回追加された場所を除く）様です。
また、WCAG 2.0 本体で、 Presentation を「提示」と訳しているのはレンダリングという観点での利用で、G117内のPresentationは「visual presentation」（視覚的表現）としての利用だという理解ですが。。。
ただ、SC 1.4.5は表現と訳している一方で、SC 1.4.6では視覚的提示と訳しているので、一度WGで方針を明確化したほうが良いのかもしれません。
＃visual presentationまで視覚的「表現」ではなく　視覚的「提示」　とするのには強い違和感があります。。。

単語 presentation をどう訳出するのか確認する。

**Comment by bakera** [comment]
結論としては、この部分も「提示」とすることが妥当であるように思います。
presentationを「提示」とすることは実は個人的にはあまり気に入っていないのですが、ともあれJIS原案作成委員としては「提示」とすることで合意しており、それで統一しています。達成基準1.4.3でも "visual presentation" を「視覚的提示」としていますので、ご確認いただければと思います。

**Comment by kentarou-fukuda** [comment]
確かにJISでは視覚的提示となっていますね。一方で、JIS内でもparticular presentationは「特定の表現」と訳されているようです。また、SC 1.4.5 http://waic.jp/docs/UNDERSTANDING-WCAG20/visual-audio-contrast-text-presentation.html　の中でも表現11箇所 提示10箇所となっているようですので、整理が必要と思います。

JISに合わせるなら「特定の表現」以外は提示とする処理でしょうか。

よろしくお願いします。

（次回のJISでは、用途で表現と提示を使い分けるように提案してみます。覚えていれば＆WCAG2.0ベースなら。。。）

**Comment by momdo** [comment]
とすると、waic.jpにある既存のWCAG 2.0訳はあくまで、JIS X 8.41-3:2016原案での合意を堅持し、手を入れるとすれば（これから作業する予定の）WCAG 2.1訳で訳語変更を検討する、という感じでしょうか。

proposalとしては：
- WCAG 2.0訳は*presentation*を例外なく「提示」と訳出する。
  -  2.0 解説書、達成方法集もこれに倣って「提示」とする
- WCAG 2.1訳に向けて、*presentation*の訳語を考える
  - 語の組み合わせによって、訳出を変えてもよいだろう。例えば、*user*を「利用者」、*user agent*を「ユーザエージェント」と現在しているように、1つの単語が異なる訳語になってよい

**Comment by momdo** [comment]
まずは、presentationが使われている箇所を全部列挙します。

**Comment by momdo** [comment]
まずは、[WCAG 2.0本体](https://www.w3.org/TR/WCAG20/)（日本語は[waic.jp](https://waic.jp/docs/WCAG20/Overview.html)のもの）について。
一応JIS X 8341-3:2016も確認した。特記なき場合は、JISもママ。

全部で20カ所。提示、表現、プレゼンテーション（！）と訳語が揺れている。

> 1.3.1 Info and Relationships: Information, structure, and relationships conveyed through **presentation** can be programmatically determined or are available in text. (Level A)
1.3.1 情報及び関係性: 何らかの形で**提示**されている情報、 構造、及び関係性は、プログラムによる解釈が可能である、又はテキストで提供されている。 (レベル A)

> 1.4.1 Use of Color:
Note: This success criterion addresses color perception specifically. Other forms of perception are covered in Guideline 1.3 including programmatic access to color and other visual **presentation** coding.
1.4.1 色の使用:
注記: この達成基準は、特に色の知覚に関するものである。その他の知覚形態については、色やその他の視覚的**提示**のコーディングへのプログラムによるアクセスも含めて、ガイドライン 1.3で網羅されている。

JISX8341-3では、「色**及び**その他の視覚的提示」とされている。

> 1.4.3 Contrast (Minimum): The visual **presentation** of text and images of text has a contrast ratio of at least 4.5:1, except for the following: (Level AA)
1.4.3 コントラスト (最低限) : テキスト及び文字画像の視覚的**提示**に、少なくとも 4.5:1 のコントラスト比がある。ただし、次の場合は除く: (レベル AA)

> 1.4.5 Images of Text: If the technologies being used can achieve the visual **presentation**, text is used to convey information rather than images of text except for the following: (Level AA)
[...] Essential: A particular **presentation** of text is essential to the information being conveyed.
1.4.5 文字画像: 使用している技術で意図した視覚的**提示**が可能である場合、文字画像ではなくテキストが情報伝達に用いられている。ただし、次に挙げる場合を除く: (レベル AA)
必要不可欠: テキストの特定の**表現**が、伝えようとする情報にとって必要不可欠である。

>1.4.6 Contrast (Enhanced): The visual **presentation** of text and images of text has a contrast ratio of at least 7:1, except for the following: (Level AAA)
1.4.6 コントラスト (高度) : テキスト及び文字画像の視覚的**提示**には、少なくとも 7:1 のコントラスト比がある。ただし、次の場合は除く: (レベル AAA)

> 1.4.8 Visual Presentation: For the visual **presentation** of blocks of text, a mechanism is available to achieve the following: (Level AAA)
1.4.8 視覚的提示: テキストブロックの視覚的**提示**において、次を実現するメカニズムが利用できる: (レベル AAA)

> 1.4.9 Images of Text (No Exception): Images of text are only used for pure decoration or where a particular **presentation** of text is essential to the information being conveyed. (Level AAA)
1.4.9 文字画像 (例外なし) : 文字画像は、純粋な装飾に用いられているか、テキストの特定の**表現**が伝えようとする情報にとって必要不可欠である場合に用いられている。 (レベル AAA)

JISX8341-3では、「純粋な装飾に用いられているか、**又は**テキストの」とされている。

> 2.2.2 Pause, Stop, Hide:
Note 3: Content that is updated periodically by software or that is streamed to the user agent is not required to preserve or present information that is generated or received between the initiation of the pause and resuming **presentation**, as this may not be technically possible, and in many situations could be misleading to do so.
2.2.2 一時停止、停止、非表示: 
注記 3: 定期的にソフトウェアによって自動的に更新されるコンテンツ、又はユーザエージェントにストリーム配信されるコンテンツでは、コンテンツ再生の一時停止と再開の操作の間に生成、又は受信される情報を保持、又は**提示**する必要はない。これは技術的に不可能であることが考えられ、多くの状況において利用者の混乱を招くことにつながる可能性があるためである。

JISX8341-3では、読点の入り方が異なる。

> Conformance Requirements
> 2. Full pages:
Note 1: For the purpose of determining conformance, alternatives to part of a page's content are considered part of the page when the alternatives can be obtained directly from the page, e.g., a long description or an alternative **presentation** of a video.
適合要件
> 2. ウェブページ全体:
注記 1: 適合の判断をするときに、例えば、詳細な説明又は映像の代替の**提示**のように、代替となるものがそのページから直接得られる場合は、ページのコンテンツの一部に対する代替コンテンツはそのページの一部であるとみなされる。

> assistive technology (as used in this document)
Note 1: functionality provided by assistive technology includes alternative **presentations** (e.g., as synthesized speech or magnified content), alternative input methods (e.g., voice), additional navigation or orientation mechanisms, and content transformations (e.g., to make tables more accessible).
(この文書で用いられている) 支援技術 (assistive technology (as used in this document))
注記 1: 支援技術が提供する機能としては、代替の**提示** (例: 合成音声や拡大表示したコンテンツ)、代替入力手法 (例: 音声認識)、付加的なナビゲーション又は位置確認のメカニズム、及びコンテンツ変換 (例: テーブルをよりアクセシブルにするもの) などを挙げることができる。

>audio-only
a time-based **presentation** that contains only audio (no video and no interaction)
音声しか含まない (audio-only)
音声のみを含んだ、時間に依存する**提示** (映像やインタラクションを含まない)。

>content (Web content)
information and sensory experience to be communicated to the user by means of a user agent, including code or markup that defines the content's structure, presentation, and interactions
コンテンツ (ウェブコンテンツ) (content (Web content))
ユーザエージェントによって利用者に伝達される情報及び感覚的な体験。コンテンツの 構造、**提示**、及びインタラクションを定義するコードやマークアップを含む。

>contrast ratio
Note 6: WCAG conformance should be evaluated for color pairs specified in the content that an author would expect to appear adjacent in typical **presentation**. Authors need not consider unusual **presentations**, such as color changes made by the user agent, except where caused by authors' code.
コントラスト比 (contrast ratio)
注記 6: WCAG に適合しているか判断する場合は、典型的な**提示**において隣接するであろうと制作者が想定するコンテンツで指定された色の組み合わせについて評価しなければならない。制作者は、ユーザエージェントによる色の変更などのように通常とは異なる**提示**を考慮する必要はない。ただし、それが制作者のコードによって起こる場合は除く。

>extended audio description
audio description that is added to an audiovisual **presentation** by pausing the video so that there is time to add additional description
拡張音声解説 (extended audio description)
映像を一時停止することで追加の説明を付加するための時間を確保し、視聴覚**プレゼンテーション**に付加した音声解説。

JISもママ。明らかな誤記。

>presentation
rendering of the content in a form to be perceived by users
提示 (presentation)
利用者が知覚できる形式でコンテンツをレンダリングすること。

>technology (Web content)
Note 2: Web content technologies may include markup languages, data formats, or programming languages that authors may use alone or in combination to create end-user experiences that range from static Web pages to synchronized media **presentations** to dynamic Web applications.
(ウェブコンテンツ) 技術 (technology (Web content))
注記 2: ウェブコンテンツ技術には、マークアップ言語、データ形式、及びプログラム言語などがあり、これらをコンテンツ制作者が単独で、又は組み合わせて用いることによって、静的なウェブページや同期したメディアによる**提示**、さらには動的なウェブアプリケーションに至るまでの様々なエンドユーザ体験を作ることができる

>video-only
a time-based **presentation** that contains only video (no audio and no interaction)
映像しか含まない (video-only)
映像のみを含んだ、時間に依存する**提示** (音声やインタラクションを含まない)。

**Comment by momdo** [comment]
解説書は次のとおり

### 1.1
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/text-equiv.xml#L8-L10
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/text-equiv.xml#L8

### 1.1.1
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/text-equiv-all.xml#L76
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/text-equiv-all.xml#L49

### 1.2.1
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/media-equiv-av-only-alt.xml#L9
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/media-equiv-av-only-alt.xml#L11

https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/media-equiv-av-only-alt.xml#L25
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/media-equiv-av-only-alt.xml#L40

https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/media-equiv-av-only-alt.xml#L140
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/media-equiv-av-only-alt.xml#L84

### 1.2.2
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/media-equiv-captions.xml#L8-L11
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/media-equiv-captions.xml#L9-L11

### 1.2.3
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/media-equiv-audio-desc.xml#L8-L9
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/media-equiv-audio-desc.xml#L9-L10

### 1.2.5
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/media-equiv-audio-desc-only.xml#L8
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/media-equiv-audio-desc-only.xml#L9

### 1.2.6
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/media-equiv-sign.xml#L8
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/media-equiv-sign.xml#L9

https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/media-equiv-sign.xml#L33
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/media-equiv-sign.xml#L27

### 1.2.7
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/media-equiv-extended-ad.xml#L8
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/media-equiv-extended-ad.xml#L9

### 1.2.8
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/media-equiv-text-doc.xml#L13
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/media-equiv-text-doc.xml#L13

https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/media-equiv-text-doc.xml#L27
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/media-equiv-text-doc.xml#L25

### 1.3
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/content-structure-separation.xml#L8-L9
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/content-structure-separation.xml#L9-L10

### 1.3.1
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/content-structure-separation-programmatic.xml#L8
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/content-structure-separation-programmatic.xml#L9

https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/content-structure-separation-programmatic.xml#L105
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/content-structure-separation-programmatic.xml#L106

https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/content-structure-separation-programmatic.xml#L164
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/content-structure-separation-programmatic.xml#L165

https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/content-structure-separation-programmatic.xml#L331
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/content-structure-separation-programmatic.xml#L332

https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/content-structure-separation-programmatic.xml#L346
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/content-structure-separation-programmatic.xml#L347

### 1.3.2
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/content-structure-separation-sequence.xml#L8
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/content-structure-separation-sequence.xml#L9

### 1.4
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/visual-audio-contrast.xml#L8
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/visual-audio-contrast.xml#L9

### 1.4.3
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/visual-audio-contrast-contrast.xml#L235
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/visual-audio-contrast-contrast.xml#L131

### 1.4.5
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/visual-audio-contrast-text-presentation.xml#L8-L12
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/visual-audio-contrast-text-presentation.xml#L9-L13

### 1.4.6
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/visual-audio-contrast7.xml#L233
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/visual-audio-contrast7.xml#L124

### 1.4.8
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/visual-audio-contrast-visual-presentation.xml#L9
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/visual-audio-contrast-visual-presentation.xml#L10

### 1.4.9
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/visual-audio-contrast-text-images.xml#L8-L11
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/visual-audio-contrast-text-images.xml#L9-L12

### 2.2.1
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/time-limits-required-behaviors.xml#L23
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/time-limits-required-behaviors.xml#L18

### 2.2.2
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/time-limits-pause.xml#L9
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/time-limits-pause.xml#L9

https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/time-limits-pause.xml#L20
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/time-limits-pause.xml#L18

### 2.4.2
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/navigation-mechanisms-mult-loc.xml#L117
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/navigation-mechanisms-mult-loc.xml#L68

### 2.4.3
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/navigation-mechanisms-focus-order.xml#L11-L12
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/navigation-mechanisms-focus-order.xml#L12-L13

https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/navigation-mechanisms-focus-order.xml#L147
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/navigation-mechanisms-focus-order.xml#L82

### 2.4.10
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/navigation-mechanisms-headings.xml#L8
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/navigation-mechanisms-headings.xml#L9

### 3.1.2
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/meaning-other-lang-id.xml#L8
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/meaning-other-lang-id.xml#L9

### 3.2.3
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/consistent-behavior-consistent-locations.xml#L8
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/consistent-behavior-consistent-locations.xml#L9

### conformance
https://github.com/w3c/wcag/blob/273cdfcad8f8930a827e1e9233352cb8cd7f0c4f/wcag20/sources/understanding/conformance.xml#L205
https://github.com/waic/wcag20/blob/d37334696768bd40775243cb6e4df80018505a5d/wcag20/sources/understanding/conformance.xml#L166

**Comment by momdo** [comment]
達成方法集

## G
- G54
- G61
- G69
- G74
- G81
- G88
- G90
- G115
- G117
- G138
- G157
- G158
- G159
- G166
- G170
- G174
- G178

## H
- H2
- H33
- H39
- H40
- H43
- H48
- H49
- H51
- H73
- H85
- H89
- H97

## C
- css
- C6
- C15
- C22
- C27
- C29
- C30

## FLASH
- flash
- FLASH31

## PDF
- pdf
- PDF6
- PDF7

## ARIA
- ARIA2
- ARIA12

## F
- F2
- F33
- F34
- F43
- F46
- F48
- F49
- F66
- F71
- F72
- F81
- F92

**Comment by momdo** [comment]
あまり票は集まっていないが、用語集の「提示」で統一して活かす方向にしてはどうか、というコメントがあったので、一旦「提示」での統一を試みることにする。
