### ISSUE TITLE
G58の手順 3. 「可用性」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag20#339]
「可用性を確認する。」が理解しにくい印象を受けます。
「利用可能かどうか確認する。」ではいかがでしょうか？

**Comment by momdo** [comment]
「可用性」がわかりにくいというのはその通りだと思います。
ついでにG58の手順をまるごと見直してみます。

**Comment by momdo** [comment]
https://waic.jp/docs/WCAG-TECHS/G58.html#G58-tests
https://www.w3.org/TR/WCAG20-TECHS/G58.html#G58-tests

手順1、2も見てみましたが、これはこれで大丈夫そうですね。
手順3はこんな感じでしょうか

原文：
Check for the availability of a link or back function to get the user back to the original location of the synchronized media content.

現行訳：
その同期したメディアコンテンツの元の場所に利用者が戻るためのリンク又は逆行機能の可用性を確認する。

改良案：
利用者がその同期したメディアコンテンツの元の場所に戻るためのリンク又は逆行機能が利用可能かどうかを確認する。
