### ISSUE TITLE
達成基準1.3.2を理解する 「一つのプログラム」は誤訳ではないか

### ISSUE THREAD

**Issue by bakera** [waic/wcag20#34]
Understanding 1.3.2 ですが、
http://waic.github.io/wcag20/Understanding/content-structure-separation-sequence.html
>重要なのは、意味が通じるコンテンツの順序を、少なくとも一つのプログラムが解釈できることである。

これは誤訳のように思います。原文は以下の通りです。

>It is important that it be possible to programmatically determine at least one sequence of the content that makes sense.

「コンテンツの順序の少なくともひとつを、プログラムが解釈できる」と言っているように思います。

**Comment by momdo** [comment]
クオリティレビューってすり抜けるものですね…。

proposal:
意味のあるコンテンツの少なくとも1つの順序をプログラムによる解釈が可能であることが重要である。

というのはどうでしょうか。
