### ISSUE TITLE
G69の手順 4. 「舞台」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag20#340]
「舞台及び舞台の変更」とありますが、原文は「setting and   setting changes.」ですので、「設定及び設定の変更」ではないでしょうか？

**Comment by momdo** [comment]
「舞台」よりかは「設定」の方が自然な気はしますね。

**Comment by momdo** [comment]
https://waic.jp/docs/WCAG-TECHS/G69.html

原文
> 1. View the synchronized media presentation while referring to the alternative for time-based media.
> 1. Check that the dialogue in the alternative for time-based media matches the dialogue in the synchronized media presentation.
> 1. Check that the alternative for time-based media has descriptions of sounds.
> 1. Check that the alternative for time-based media has descriptions of setting and setting changes.
> 1. Check that the alternative for time-based media has descriptions of actions and expressions of any 'actors' (people, animals etc).
> 1. If the alternate version(s) are on a separate page, check for the availability of link(s) to allow the user to get to the other versions.

現行訳
>1. 時間依存メディアに対する代替を参照しながら、同期したメディアによる提示を閲覧する。
>1. 時間依存メディアに対する代替にある発話内容が、同期したメディアによる提示での発話内容と一致していることを確認する。
>1. 時間依存メディアに対する代替に、音の説明があることを確認する。
>1. 時間依存メディアに対する代替に、舞台及び舞台の変更の説明があることを確認する。
>1. 時間依存メディアに対する代替に、(人、動物など) 「登場人物」の行動及び表現の説明があることを確認する。
>1. 代替版が別のページにある場合、利用者が別の版に到達できるリンクの可用性を確認する。

改良案
1. ママ
2. [dialogue](https://eowf.alc.co.jp/search?q=dialogue) を「会話」として: 時間依存メディアに対する代替での会話が、同期したメディアによる提示での会話と一致していることを確認する。
3. ママ
4. 時間依存メディアに対する代替に、設定及び設定の変更の説明があることを確認する。
5. [actor](https://eowf.alc.co.jp/search?q=actor) を「当事者」として: 時間依存メディアに対する代替に、「当事者」(人、動物など) の行動及び表現の説明があることを確認する。
6. 代替版が別のページにある場合、利用者が別の版に到達できるリンクが利用可能かどうかを確認する。

**Comment by momdo** [comment]
ついでに「舞台」で検索すると、G173にもありましたが、これはこれとして別issueで。

**Comment by bakera** [comment]
上のほうの「解説」の箇所では
" the setting and background,"
を
「場面や背景」
としているので、「場面」でそろえるのもありですね。

**Comment by momdo** [comment]
手持ちの辞書はsetingを舞台としていますが、どうにも舞台がしっくりくる気がしないので、
[舞台の類語](https://thesaurus.weblio.jp/content/%E8%88%9E%E5%8F%B0)に太田さんが言及している場面も見えますし、場面で揃えてみますか。
