### ISSUE TITLE
G121、G55の手順 1. 「インスタンス」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag20#342]
原文「first   instance」に対して「最初のインスタンス」というのは何を指しているのか難しい表現のように感じられます。「初出の箇所」ではいかがでしょうか？

**Comment by momdo** [comment]
意訳な感じにするしかないですかね…何か思いつきますか？ @bakera @caztcha

**Comment by caztcha** [comment]
個人的には、澤田さん案 (「初出の箇所」と訳す) がしっくり来ます。

**Comment by momdo** [comment]
G55/G121以外の検索：

### H45
- https://waic.jp/docs/WCAG-TECHS/H45.html
- https://www.w3.org/TR/WCAG20-TECHS/H45.html

> 別のリソースを用いて説明することの利点は、同じ画像を複数のインスタンスで簡単に再利用できることにあり、
 An advantage of using a separate resource for the description is that it is easily reusable for multiple instances of the same image,

### F50
- https://waic.jp/docs/WCAG-TECHS/F50.html
- https://www.w3.org/TR/WCAG20-TECHS/F50.html
>手順
点滅しているそれぞれのインスタンスに対して:
Procedure
For each instance of blinking content:

### ARIA11
- https://waic.jp/docs/WCAG-TECHS/ARIA11.html
- https://www.w3.org/TR/WCAG20-TECHS/ARIA11.html
> たとえば、navigation ロールがウェブページ上で複数回使用される場合、各インスタンスは aria-labelledby を使用して、指定された一意のラベルを持ってもよい:
For instance, if a navigation role is used multiple times on a Web page, each instance may have a unique label specified using aria-labelledby: 

### SCR22
- https://waic.jp/docs/WCAG-TECHS/SCR22.html
https://www.w3.org/TR/WCAG20-TECHS/SCR22.html
>点滅しているコンテンツのそれぞれのインスタンスに対して:
（中略）
点滅しているコンテンツのそれぞれのインスタンスに対して、2. の結果が真である。
For each instance of blinking content:
...
For each instance of blinking content, \#2 is true.

###（おまけ） H54
- https://waic.jp/docs/WCAG-TECHS/H54.html
- https://www.w3.org/TR/WCAG20-TECHS/H54.html
> H54: 単語の定義実体を特定するために、dfn 要素を使用する
> H54: Using the dfn element to identify the defining instance of a word
