### ISSUE TITLE
G166の手順 1. 「音声代替」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag20#344]
「音声代替」とありますが、原文は「audio   alternative」ですので、「音声による代替」ではないでしょうか？

**Comment by momdo** [comment]
ざっくり検索したところ、

- 「音声代替」は指摘いただいたG166のみ
- 「音声による代替」は、G166の別箇所と、media-equiv-av-only-alt(Understanding 1.2.1)にあるようですね。
