### ISSUE TITLE
H62 「読み方」表記揺れ

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag20#348]
「読みかた」と「読み方」が混在しています。

**Comment by momdo** [comment]
これはH62の中でどちらかで統一されていればそれでよい、ということでしょうか。 @SawadaStdDesign 

個人的にはどちらかにさえ統一されていれば、どちらでもいい気がしますが、何か知見はありますか？ @caztcha

**Comment by SawadaStdDesign** [comment]
H62は近い場所で揺れていたので気になったのでした。

本来は全体で統一、ということなのでしょうけど... 
特に全体を見直す必要があるほどのクリティカルな問題ではないと思いますので、H62の中で！

**Comment by caztcha** [comment]
常用漢字表を見ると、「表の見方及び使い方」などと表記されていますし、以前参考にした「[マニュアル作成の進め方とわかりやすいマニュアルのポイント－実践テクニカルライティングセミナー](http://www.yamanouchi-yri.com/index.htm)」 を見ても「マニュアル作成の進め方」「見出し構成と見出し名の考え方」などと書かれていますので、「方」で統一、でいいのではと思います。

**Comment by momdo** [comment]
@caztcha  ありがとうございます。

では「読み方」でいきましょう。（なお、「読みかた」で検索したところ、H62しかヒットしませんでした。）
