### ISSUE TITLE
C6の解説 「構造要素」「依然として」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag20#349]
「構造要素を使用することで、スタイリングが利用できない場合にコンテンツの意味を依然として決定できることを保証する。」が理解しにくい印象を受けます。
「構造的な要素を使用することで、スタイリングが利用できない場合でもまだコンテンツの意味を決定できることを保証する。」ではいかがでしょうか？

**Comment by momdo** [comment]
「構造要素」→「構造的な要素」とした方がわかりやすそうですね。C6の解説全体も合わせて見直してみたいと思います。

**Comment by momdo** [comment]
https://waic.jp/docs/WCAG-TECHS/C6.html#C6-description

原文
> The objective of this technique is to demonstrate how visual appearance may be enhanced via style sheets while still maintaining a meaningful presentation when style sheets are not applied. Using the positioning properties of CSS2, content may be displayed at any position on the user's viewport. Using structural elements ensures that the meaning of the content can still be determined when styling is not available.

現行訳
> この達成方法の目的は、スタイルシートが適用されなくても意味の伝わる提示がなされるようにした上で、スタイルシートを使って見栄えをさらに良くする方法を示すことである。CSS2 の配置関連のプロパティを使用すれば、コンテンツを利用者のビューポート内の任意の位置に配置することができる。構造要素を使用することで、スタイリングが利用できない場合にコンテンツの意味を依然として決定できることを保証する。

改良案
この達成方法の目的は、スタイルシートが適用されていない場合でも意味のある提示を維持しながら、スタイルシートを介して視覚的外観をどのように向上させることができるかを示すことである。CSS2 の配置プロパティを使用して、コンテンツを利用者のビューポートの任意の位置に表示できる。構造的な要素を使用することで、スタイルが利用できない場合でもコンテンツの意味を判断できることを保証する。
