### ISSUE TITLE
視力表現の訳出について

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#36]
例えば、<a href="http://waic.github.io/wcag20/Understanding/visual-audio-contrast-contrast.html">達成基準 1.4.3 を理解する</a>で、

> 20/40 の視力は、おおよそ 1.5 のコントラスト感度低下と関連付けられているという経験的事実がある[ARDITI-FAYE]。

これは、欧米でよく用いられる分数表現のままなので、日本人に馴染みのある小数表現として訳出してはどうか？（伊敷さんに調べていただく）

参考URL
- https://www.alc.co.jp/speaking/article/kango/21.html
- https://ja.wikipedia.org/wiki/%E8%A6%96%E5%8A%9B#.E8.A6.96.E5.8A.9B.E3.81.AE.E8.A1.A8.E8.A8.98
- https://www.recruit-dc.co.jp/archives_english/no0808/

**Comment by cocktailz** [comment]
大変遅くなりましたが、今月眼科を受信した際、主治医に確認してきました。
結論としては20/20を0.5のように表記してもよいそうです。

**Comment by momdo** [comment]
@cocktailz 確認ありがとうございます。

と言うわけで、日本人に馴染みの小数表記にしたいと思いますけど、置換するか括弧書き等で追記するかどちらの方が好ましいですかね。 @bakera 

他にもご意見あれば伺いたく。

**Comment by bakera** [comment]
いちおう原文のこしで括弧がきでしょうか。
>約 20/80 まで視力の低下した利用者
→約 20/80 (0.25) まで視力の低下した利用者
