### ISSUE TITLE
"rivers of white"の訳語をどうするか

### ISSUE THREAD

**Issue by bakera** [waic/wcag20#383]
G169, F88などで「余白 (隙間) の川」という言葉が出てきます。

https://waic.jp/docs/WCAG-TECHS/G169.html
https://waic.jp/docs/WCAG-TECHS/F88.html

原文は "rivers of white" です。
ちょっと丁寧に注釈をつけすぎた訳となっている感じがしております。
今のルール的には、普通に「白い川」とか訳した上で訳注にするべきなのかなと……。

**Comment by momdo** [comment]
つまるところ https://en.wikipedia.org/wiki/River_(typography) こういうことだと思うので、訳注に適当な日本語URLをどこから持ってくるか次第でしょうか。

**Comment by terkel** [comment]
@bakera 欧文組版ではそのまま「リバー」とすることが多いようです。手元の資料では『増補改訂版欧文組版』『タイポグラフィ・ハンドブック』でリバーとなっています。個人的にも、リバーとした上で訳注があるのがわかりやすい気がします。

**Comment by bakera** [comment]
リバーはリバーとして、rivers of white をどうするかですが、以下のような選択肢があがりました。

- カタカナで「リバーオブホワイト」とする
- 「余白のリバー」のようにwhite部分は訳す
- そもそも「リバー」だけで rivers of white の意味になるので単に「リバー」とする
- 原文との対応が分かりやすいように「リバー (rivers of white)」と表記してはどうか

最後の案がよさそうということで、いったん「リバー (rivers of white)」としたいと思います。

**Comment by momdo** [comment]
解説書1.4.8にもあり。
https://waic.jp/docs/UNDERSTANDING-WCAG20/visual-audio-contrast-visual-presentation.html
