### ISSUE TITLE
「アクセシビリティサポート」に半角スペースがない

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag20#385]
「アクセシビリティ サポーテッド」という表記に統一されていると思いますが、次のページのように「アクセシビリティサポート」の場合には半角スペースが入っていません。
https://waic.jp/docs/UNDERSTANDING-WCAG20/conformance.html#uc-accessibility-support-head

統一するとすれば、「アクセシビリティ サポート」でしょうか？

**Comment by bakera** [comment]
「アクセシビリティ サポート」と半角スペース入れる形で統一する方向にしたいと思います。
