### ISSUE TITLE
SC 1.4.3解説書 視覚的なガイドライン

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#386]
https://waic.github.io/wcag20/Understanding/visual-audio-contrast-contrast.html

> ロゴ及びロゴタイプの範囲を超える企業の視覚的なガイドラインは含まれない。

ここは視覚的よりビジュアルとした方が意味が通るのでは？

**Comment by bakera** [comment]
原文これですね。
> Corporate visual guidelines beyond logo and logotype are not included in the exception.

**Comment by bakera** [comment]
ビジュアルガイドラインはビジュアルガイドラインとしたほうが良いように思います。

それはそれとして、ちょっとこの訳分全体が伝わりにくいように思います。
単に「含まれない」となっていますが、"not included in the exception." なので、「この例外には含まれない」くらいのほうが良いのではないかと思います。
beyondを「超える」としているのが分かりにくい感じがしており、「以外の」とかでも良いのではないでしょうか。

ロゴ及びロゴタイプ以外の企業のビジュアルガイドラインは、この例外には含まれない。

といったところでどうでしょうか。
