### ISSUE TITLE
G205の事例で、コード例と対応する説明テキストの整合性が取れていない

### ISSUE THREAD

**Issue by tokimari** [waic/wcag20#401]
https://github.com/waic/wcag20/issues/190 で、コード例は訳出せず原文ままとする、とありましたが、G205に コード例と対応する説明テキストの整合性が取れていない箇所がありました。ご検討お願いします。

https://waic.jp/docs/WCAG-TECHS/G205#G205-ex1

### 該当箇所
> オンラインフォームで「必須項目は赤で示され、(必須) とマーク付けされている。」と指示されている。「(必須)」という手がかりが label 要素の中に含まれる。
> ```
> <label for="lastname" class="required">Last name (required): </label>
> ```

### 修正案1

> オンラインフォームで「必須項目は赤で示され、(必須) とマーク付けされている。」と指示されている。「(必須)」という手がかりが label 要素の中に含まれる。
> ```
> <label for="lastname" class="required">Last name (必須): </label>
> ```

※この場合Last nameも訳すべきでしょうか

### 修正案2

> オンラインフォームで「必須項目は赤で示され、(required) とマーク付けされている。」と指示されている。「(required)」という手がかりが label 要素の中に含まれる。
> ```
> <label for="lastname" class="required">Last name (required): </label>
> ```

**Comment by momdo** [comment]
@tokimari 

isuueありがとうございます。これは、修正案2があるべき姿ですね。

**Comment by tokimari** [comment]
ご確認ありがとうございます！２の方で進めます 😄
