### ISSUE TITLE
G167 解説の注記の誤訳

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#403]
原文 https://www.w3.org/TR/WCAG20-TECHS/G167.html#G167-description
> Note: The field must also have a programmatically determined name, per Success Criterion 4.1.2.

訳文 https://waic.github.io/wcag20/Techniques/G167.html#G167-description
> 注記: 達成基準 4.1.2 を満たすため、このボタンはプログラムによる解釈が可能な名前 (name) を持っていなければならない。

ボタンとは書いておらず、フィールドの誤りと思われます。（解説についても微妙に翻訳が怪しい？）

**Comment by bakera** [comment]
ついでに言うと also の訳も落ちているように思えますね。
この例のボタンによるラベルに加えて、プログラムによる解釈が可能な名前 *も* 必要というニュアンス。
