### ISSUE TITLE
検索結果に表示される過去の解説書への対応

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag20#404]
Slackの以下の @bakera さんの投稿を引き継ぎます。
https://waic-jp.slack.com/archives/CFL2JR1FB/p1584093128126000

以下のような検索をすると、古いバージョンの解説書が検索結果に表示されます。
https://www.google.com/search?q=wcag+2.0+1.1.1

古い翻訳をアップしたままにしておくのでしたら、古い翻訳から新しい翻訳への動線を作り、新しい翻訳があることを明示した方が良さそうです。

**Comment by momdo** [comment]
原文の古いバージョンで
https://www.w3.org/TR/2015/NOTE-UNDERSTANDING-WCAG20-20150226/
みたいな表示は出てくるので、これにあわせるのはありかもしれません。
（とはいえ表紙だけの対応なので、なんだかなあ、という気はするのですが。）

**Comment by jidaikobo-shibata** [comment]
なるほど、`aria-modal="true"`。
やるなら全ページにあった方がいいような気がしますね。

**Comment by bakera** [comment]
以下のPRで冒頭訳註を追加しているので、これで対応済みとしたい。
https://github.com/waic/wcag20/pull/424
