### ISSUE TITLE
Typo in media-equiv-captions

### ISSUE THREAD

**Issue by masuP9** [waic/wcag20#407]
s/もらたす/もたらす/

```
<p>現在のところ、時間依存の素材に対してキャプションを作成することは困難であるかもしれないことが認められている。これは、キャプションが利用可能になるまで情報を延期する、又は少なくともキャプションが利用可能になるまでの期限で、ろう者にアクセシブルでない時間依存のコンテンツを公開するという選択に直面するコンテンツ制作者をもらたす可能性がある。時間とともに、配信プロセスにキャプション付けを組み込むツールだけでなく、キャプションを付けるためのツールも、そのような遅延を短縮する又は除去するだろう。</p>
```

https://github.com/waic/wcag20/blob/ed0a2ef10bccbe2e68d7550c64c510d3dc9b13e3/wcag20/sources/understanding/media-equiv-captions.xml#L10

**Comment by momdo** [comment]
via: [オンライン]WCAGもくもく会 #8 - connpass 
https://ca11y.connpass.com/event/176129/
