### ISSUE TITLE
達成基準 1.1.1の「テスト」がわかりにくいという意見

### ISSUE THREAD

**Issue by bakera** [waic/wcag20#410]
WCAG 2.0 の達成基準の内容がわかりにくいというコメントがあり。

https://twitter.com/earlgrayMK/status/1273915991320170497
>WCAGの達成基準 1.1.1 非テキストコンテンツの「非テキストコンテンツが、テキストで提示されると無効になるテスト又は演習のとき」ってどういう時？🤔

https://waic.jp/docs/WCAG20/Overview.html#text-equiv
>テスト: 非テキストコンテンツが、テキストで提示されると無効になるテスト又は演習のとき、テキストによる代替は、少なくともその非テキストコンテンツを識別できる説明を提供している。

なお解説書にはそれなりに長文の解説がある。
https://waic.jp/docs/UNDERSTANDING-WCAG20/text-equiv-all.html
>テスト又は演習が、部分的又は全体的に非テキストの形式で提示されなければならないことがある。そのテスト又は演習は、聴覚又は視覚を用いて行う必要があるため、音声又は視覚情報はテキストに変換することのできないものとして提示される。例えば、ヒアリングテストは、もしテキストによる代替が提供されるなら、効力がないだろう。視覚能力向上のための演習も、テキスト形式では同様に意味を成さない。さらに、テキストによる代替のあるスペルのテストもあまり効果がない。このような場合には、テキストによる代替は非テキストコンテンツの目的を説明するために提供されることが望ましい。もちろん、そのテキストによる代替は、テストに合格するために必要な情報と同じものは提供しないことになる。

**Comment by momdo** [comment]
WCAG 2.2のレポジトリに複写したのでClose
