### ISSUE TITLE
公開されているWCAG 2.0の「適合要件」の「非干渉」が間違っている

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag20#417]
https://waic.jp/docs/WCAG20/Overview.html#conformance-reqs
の非干渉が「2.1.2 - フォーカス移動」となっています。

https://waic.github.io/wcag20/WCAG20/Overview.html#conformance-reqs
githubのほうは「2.1.2 - キーボードトラップなし」となっていて正しいようです。

**Comment by momdo** [comment]
@bakera

こちら、しれっとHTMLを差し替える必要がありそうです。

**Comment by bakera** [comment]
お待たせしました。修正を本番反映いたしました。

https://waic.jp/docs/WCAG20/Overview.html

**Comment by momdo** [comment]
反映済みなのでCloseします。
