### ISSUE TITLE
WCAG 2.0解説書/達成方法集のWAICサーバー反映（2021-04分）

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#419]
3/26にWAICレビュー依頼済み。コメントなし。
太田さんに公開作業を進めてもらう。

**Comment by momdo** [comment]
WCAG 2.1解説書/達成方法集 waic/wcag21#945 についても進めてもらう。

**Comment by bakera** [comment]
本番に反映しました。
https://waic.jp/docs/UNDERSTANDING-WCAG20/Overview.html
https://waic.jp/docs/WCAG-TECHS/Overview.html

**Comment by momdo** [comment]
@bakera 

早速の作業ありがとうございます。ニュースリリースは必要ですかね…？

**Comment by momdo** [comment]
公開済みなのでCloseしておきます。
