### ISSUE TITLE
G155: サイド確認→再度確認

### ISSUE THREAD

**Issue by bakera** [waic/wcag20#422]
問い合わせフォームより:

文書の翻訳ありがとうございます。
解説の文章で気になった点です。
結果として入力内容をサイド確認することにつながる。
↓
結果として入力内容を再度確認することにつながる。
よろしくお願いいたします。

**Comment by bakera** [comment]
該当箇所と原文:

https://waic.jp/docs/WCAG-TECHS/G155.html
>送信ボタンとは別のコントロールとしてチェックボックスを提供することで、処理を続行するために利用者はチェックボックスの選択と送信ボタンの動作の両方をしなければならず、結果として入力内容をサイド確認することにつながる。

https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G155.html
>Providing the checkbox as a separate control from the submit button forces the user to "double-check", as they must both select the checkbox and activate the submit button for the transaction to proceed. 

単に直せばいいと思いきや、微妙に訳が怪しい気がしますね。
なおWCAG 2.1達成方法集では訳し直されていて、以下のようになっています。

https://waic.jp/docs/WCAG21/Techniques/general/G155
>送信ボタンとは別のコントロールとしてチェックボックスを提供することで、処理を続行するために利用者はチェックボックスの選択と送信ボタンの動作の両方をしなければならず、「ダブルチェック」を強制させる。

**Comment by bakera** [comment]
2.1の訳もすこしおかしい感じがしますね。文末の「強制させる」の主語は「利用者は」?
素直に訳すとこんな感じなのでしょうか。

送信ボタンとは別のコントロールとしてチェックボックスを提供することは利用者に「ダブルチェック」を強制し、これによって、処理を続行するにはチェックボックスの選択と送信ボタンの動作の両方をしなければならなくなる。

**Comment by momdo** [comment]
https://github.com/waic/wcag21/commit/1ab191f2e519fd0eb53e297ff3d7f8b8c25892c3 にて修正済みなのでClose
