### ISSUE TITLE
「ブロックスキップ : 達成基準 2.4.1 を理解する」のmoreが訳出されていない

### ISSUE THREAD

**Issue by bakera** [waic/wcag20#65]
http://waic.github.io/wcag20/Understanding/navigation-mechanisms-skip.html

>The intent of this Success Criterion is to allow people who navigate sequentially through content more direct access to the primary content of the Web page. 
>この達成基準の意図は、コンテンツ内を一つずつ順を追って行き来している利用者がウェブページのメインコンテンツへ直接移動できるようにすることである。

原文 more direct access の more が訳出されていませんが、この有無でニュアンスが異なってくるのではないでしょうか。
( という議論が WG2 でありました )

**Comment by momdo** [comment]
#47 で対応します（というか偶然にも私の受け持ちなのですが）。
現在のところ、
> この達成基準の意図は、コンテンツを順番にナビゲートする人にウェブページのメインコンテンツへより直接的なアクセスをできるようにすることである。

とする予定ですが、いかがでしょうか。 @bakera

**Comment by bakera** [comment]
ありがとうございます。それで良いと思います!

**Comment by momdo** [comment]
では、上記のとおり対応しておきます（このissueは閉じておきます。）
