### ISSUE TITLE
ブランチ運用ルールを決める

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#67]
@bakera さんが決めると言っていたと記憶してますが、どうなってますか？

**Comment by bakera** [comment]
基本、GitHub Flowでの運用を考えています。
以下のようなフローを想定しています。

・masterブランチがリリース可能な最新の状態となるようにする
　(GitHub Pagesでもmasterの内容が見えるようにする)

・作業時にはブランチを切って作業を開始する
　ブランチの名前は作業の性質に応じたものとする

・作業中は適宜ブランチをpushする

・作業が終わったところでプルリクエストを出す

・作業内容に問題ないことが確認出来たらmasterにマージする

GitHub Flowではリリースブランチを使用しないので、「一部機能だけを公開」のようなことがやりづらいのですが、いままでのWG4の作業でそういうことが必要になったことはないので、問題ないだろうと思っています。

どちらかというと、masterを整備することが課題になります。
現状は wg_translation ブランチがmasterのような扱いになっていますが、おそらく単純にmasterにマージすることは難しいと思われ、このブランチを強引にmasterに置き換えるような処理が必要になるかもしれません。

**Comment by momdo** [comment]
基本それでよいと思います。`master` を本来の意味でのmasterにしたほうがいろいろと分かりやすいと思います。

**Comment by bakera** [comment]
意外とあっさりmasterにマージできましたので、masterを運用するということで。

**Comment by momdo** [comment]
とりあえずの運用は決まったので、一旦Closeします。
何かあればReOpenするなりしてもらえれば。
