### ISSUE TITLE
達成方法集から訳註としてAS情報へのリンクを張る

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#68]
# 動機
- 例えば `longdesc` がアクセシビリティ サポーテッドの観点からは推奨できないものであるが、そうとは知らずリソースを参照してしまうことを防ぎたい。
- どの程度サポートされる達成方法なのかを読者に情報提供することは有用だと思われる。

# 方法
- H45は達成不可能とされているので、その旨とともに訳註としてリンクを張る
- 要注意や達成可能のものもリンクを張る

# HTML断片案
## 達成不可能の場合
<p>WAIC では H45 に関する<a href="https://waic.jp/docs/as/">アクセシビリティ・サポーテッド（AS）情報</a>を提供している。
<p>2014 年 6 月版の <a href="https://waic.jp/docs/as/info/201406/H45.html">アクセシビリティ・サポーテッド（AS）情報：H45</a> では、「達成不可能」と評価されている。WAIC はウェブ制作者がこの達成方法を使用することを推奨しない。

## 要注意の場合
<p>WAIC では H35 に関する<a href="https://waic.jp/docs/as/">アクセシビリティ・サポーテッド（AS）情報</a>を提供している。
<p>2014 年 6 月版の <a href="https://waic.jp/docs/as/info/201406/H35.html">アクセシビリティ・サポーテッド（AS）情報：H35</a> では、「要注意」と評価されている。WAIC はウェブ制作者にこの達成方法が一部の環境では動作しないことに注意を促すものである。

## 達成可能の場合
<p>WAIC では H24 に関する<a href="https://waic.jp/docs/as/">アクセシビリティ・サポーテッド（AS）情報</a>を提供している。
<p>2014 年 6 月版の <a href="https://waic.jp/docs/as/info/201406/H24.html">アクセシビリティ・サポーテッド（AS）情報：H24</a> では、「達成可能」と評価されている。WAIC はこの達成方法が検証した環境で広く動作すると判断している。

**Comment by bakera** [comment]
良いと思いますがどう実装したものですかね。XSLTをがんばるのかどうか……。

**Comment by momdo** [comment]
XSLTで頑張るほうがヒューマンエラーの紛れが少ないと思ってはいます（問題はどのファイルにテンプレートを仕込んで置くのが後々理解が容易なのか、といった感じでしょうか。）
