### ISSUE TITLE
英語リソースへのリンクテキストの表記を統一する

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#87]
解説書と達成方法集で現状、次のように混在しているので、どれかに統一するか、何らかの規則でもって揃えた方がよいのでは、という話。

- 原文ママとしているもの
- 原文ママに(英語)と添えているもの
- 訳出した上で(英語)と添えているもの

確か、以前どこかで(英語)は付けるという話だった気がしてます。

**Comment by bakera** [comment]
WCAG本体訳の作法としては、
・英文ドキュメントへのリンクは原文ママ、「(英語)はつけない」
・対応する日本語版がある場合には隣に [日本語訳] というリンクを追加
となっていますので、このルールで統一するのが良いのではないかと思います。

**Comment by momdo** [comment]
最初にissueを書いたときは、解説書や達成方法集での、概要やこの文書のステータスにあるリンクを想定していました。
仮に、前述の日本語訳リソースのあるものに「原文へのリンク+[日本語訳へのリンク]」を適用しようとすると、例えば、解説書の「達成基準 x.x.x の達成方法及び失敗例」の今のスタイルと整合性がとれないため、WCAG 2.0仕様訳と厳密にあわせる必要はないのではという意見があった、と記憶しています。
それでも、達成方法集にある関連リソースにおけるリンクは、W3C仕様、MDNやWikipediaがあるとすれば「原文へのリンク+[日本語訳へのリンク]」はそれなりの意義があるのかもしれません（が、どこまで面倒を見るのか、という別の問題はあります）。

そう考えるとリンクの種類については、

- 原文（英語リソース）のみ
- waic.jpに存在するWCAG 2.0関連リソース
- その他の日本語訳のあるリソース

と3つに分けて考えた方がよいのかもしれませんね。

**Comment by bakera** [comment]
原則、リンク先の文書のタイトルに合わせましょう。
いったん以下のルールとしたいと思います。

・英語の文書へのリンクであれば、英語のタイトルをそのままリンクテキストとする。この時、リンク先が英語の文書であることは容易に想像できるので、「(英語)」は不要。
・日本語の翻訳文書へのリンクであれば、翻訳文書の訳されたタイトルをそのまま持ってくる
・翻訳文書でありながら英語のタイトルのままであるような場合、言語が不明となるため、この場合には「(日本語訳)」とつけることを検討する。

**Comment by bakera** [comment]
日本語版・英語版のリンクを併記するような場合には、それぞれにタイトルを書くと冗長となるため、例外とする。

**Comment by bakera** [comment]
マージ済みですのでクローズします。
