### ISSUE TITLE
識別名→名前 (name)

### ISSUE THREAD

**Issue by bakera** [waic/wcag20#96]
G10のタイトルや本文などに「識別名」という言葉が残っていることに気づきました。「識別名」は2010年版での "name" の訳語ですが、2016年版では「名前 (name)」としており、変更する必要がありそうです。
https://waic.github.io/wcag20/Techniques/G10.html

**Comment by momdo** [comment]
https://github.com/waic/wcag20/search?utf8=%E2%9C%93&q=%E8%AD%98%E5%88%A5%E5%90%8D
GitHubの検索、あんまり信頼性がないですね…

ローカルでの検索結果によれば、Understandingは次の2箇所。
https://github.com/waic/wcag20/blob/ec8dcf455cd8af898d3ea04d068a7c3be7f5b657/wcag20/sources/understanding/consistent-behavior-consistent-functionality.xml#L46

https://github.com/waic/wcag20/blob/ec8dcf455cd8af898d3ea04d068a7c3be7f5b657/wcag20/sources/understanding/conformance.xml#L173

Techniquesは数が多いので番号だけ列挙すると、
G10、G108、G167、G197、G201、H91、F82、F86、PDF12
になるようです。

**Comment by bakera** [comment]
2018-01-25WG4ミーティングにて方向性を確認。
識別名→名前 (name)、役割→役割 (role) は全体的に修正してしまい、クオリティレビューの結果反映と同時に全体レビューに回す方針としました。
