### ISSUE TITLE
travis.ymlの見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag20#99]
- <a href="https://github.com/waic/wcag20/tree/master/wcag20/Techniques/ua-notes">ua-notes</a>は手動でpushしたが、自動でpushというかコピーされるようにしておきたい
- dist: precise として暫定対応したが、そんなことせずとも動作するようにしたい 関連：https://github.com/waic/wcag20/commit/182859942faaa5076a79f86c9a13116793551d29
- Pull Requestをするとbuildされるが、pushまでされてしまうのでこれを回避したい

**Comment by bakera** [comment]
https://docs.travis-ci.com/user/pull-requests/ によると、
```
'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
```
みたいな書き方ができるっぽい。

**Comment by momdo** [comment]
自分が見かけたのはこれですね。
https://qiita.com/azu/items/8afe3a9efdfb4d7646c7
```
test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && したいこと
```
いずれにせよshでもにょもにょ、といったところでしょうか。GitHubでトライアンドエラーしたくないんですよねえ…何かいい方法はないでしょうか。

**Comment by momdo** [comment]
ping @masuP9 
なんかこう、このレポジトリにpushせずにTravisを試せる業とかないですかね…

**Comment by momdo** [comment]
このレポジトリーはメンテナンスしない方針なのでClose
